### ISSUE TITLE
Github-Hostnames can begin with protocol

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/vscode-github#100]
As stated in #59 the hostname given by users could begin with protocol like `http` or `https`.
This should be considered during URL creation.

**Comment by KingHenne** [comment]
Are you sure you are also handling `https` correctly? Because when I entered the hostname with `https://` while setting up the token it failed silently. It worked when I removed the protocol.

**Comment by KnisterPeter** [comment]
I have to refactor the whole url handling and clean up the source of it. So there may be bugs currently which lead to this behaviour. I'll create a new issue for this.
