### ISSUE TITLE
Feature request: show pull request code review comments

### ISSUE THREAD

**Issue by danvk** [KnisterPeter/vscode-github#103]
If your PR has been reviewed on GitHub, it'd be great to see those comments in vscode. Even better would be a way to respond to them from inside vscode!

**Comment by ProLoser** [comment]
Responding seems like an edge case that gets really complex because there's inline comments and thread comments and approve/reject comments. I opened #104 so that I could at least quickly respond. I do think it'd be interesting to see a light breakdown of the statuses though (upon hover?)

**Comment by KnisterPeter** [comment]
This is already in progress in #40 
But as @ProLoser mentioned this is very hard (lot of work). But I want it definitely in there.

**Comment by ProLoser** [comment]
I say do small pieces at a time instead of trying to knock it all out at once.

**Comment by paulirish** [comment]
Wow, I'm in good company wanting this feature. Three top-notch open source dudes.

Well, as I posted in #105, I think that https://github.com/philschatz/atom-pull-requests has done a decent job with the  UI. Would love to see it in vscode. And totally understand it's not a trivial task.  :)

**Comment by KnisterPeter** [comment]
I'll definitely add this feature. But it will need some time to implement and I have to rethink the UI part since UI isn't customizable in vscode.
But yes, this is a must have.

**Comment by KnisterPeter** [comment]
Work started in #118 and #119

**Comment by bryantebeek** [comment]
This would really be an awesome feature. Was looking for it today and it would greatly improve the reviewing experience.

**Comment by brianjmurrell** [comment]
To be clear about requirements, when somebody reviews my PR and adds comments associated with lines of code in my PR, I want to be able to see those comments in VS Code so that I can make the requested code changes right there in VS Code without having constantly swap windows between VS Code and my browser on Github.

**Comment by KnisterPeter** [comment]
@brianjmurrell Hi there, I think you meant to comment in this extensionion: https://github.com/microsoft/vscode-pull-request-github, don't you?

**Comment by brianjmurrell** [comment]
> @brianjmurrell Hi there, I think you meant to comment in this extensionion: https://github.com/microsoft/vscode-pull-request-github, don't you?

Oh, hrm.  Yes, I think I did.  Sorry about that.  Too many similar extensions.  :-/  The double-edged blade of choice.
