### ISSUE TITLE
Feature Request: Make Pull-Request in status bar clickable

### ISSUE THREAD

**Issue by ProLoser** [KnisterPeter/vscode-github#104]
I just saw this for the first time (which is pretty cool):

![image](https://cloud.githubusercontent.com/assets/67395/25925387/1cbc9850-359d-11e7-894e-28d225025ab3.png)

First thing I tried to do was click on it. Nothing happened. Is this broken (I'm on enterprise) or was there never a click behavior? Can you make this a link to the webpage (maybe the type that has a relevant hover state too).

**Comment by KnisterPeter** [comment]
The status bar item is clickable when the status is mergeable (green). Then the merge command is tied to it and upon click it is possible to merge the pull request.

AFAK hovering is not possible in the UI of vscode.

Maybe there is a good command to connect in case of error/pending status? But opening the website would be too different from merging.

**Comment by ProLoser** [comment]
I don't like that clicking on such a small button can perform such a
potentially dangerous action. Is there no thoughts on configuring this? In
my mind if a success allows you to merge (a potentially typical response)
then a failure should allow you to inspect or follow up (the other typical
response).

Honestly I'd rather both success and failure take me to the website to
perform the merge there instead of doing it through your UI because merged
are usually never that simple. You always end up adding a comment or
closing issues or choosing a specific way to merge or at least one other
action. I would never ever trust a status bar button to give me enough
information to safely merge code together.

**Comment by KnisterPeter** [comment]
@ProLoser Why would you not trust a status bar?
BTW a click on the status bar icon will open up the 'merge, rebase, squash' dialog. So you could choose what merge operation you would like to do. Currently there is no option to add a comment tho, but that may be a good option.

What would increment your trust in such an operation and where is the difference in your IDE vs github?

**Comment by ProLoser** [comment]
I need to look at diff's and comments and files. I don't like to blindly
merge code without review. People can sneak in extra commits without your
knowledge and as long as the builds pass you won't know better. It's just
bad practice imo to merge without reviewing actual diff's.

**Comment by KnisterPeter** [comment]
Sure. Thats a good point. So if reviews are possible with this extension, then you could better trust it maybe.
Right now, I'll use this call only for PR I've created on my own for the same reason.

**Comment by KnisterPeter** [comment]
Will be released with 0.17
