### ISSUE TITLE
feature request: view/edit Pull Request comments inline

### ISSUE THREAD

**Issue by paulirish** [KnisterPeter/vscode-github#105]
Basically I'm dying to have the functionality of https://github.com/philschatz/atom-pull-requests

I don't know if you want to take on that scope here, but i'd pay money for whoever ships this plugin. :)

Cheers

**Comment by ProLoser** [comment]
This is pretty much where the discussion from #103 went lol

**Comment by paulirish** [comment]
I am blind. :)   Cheers.
