### ISSUE TITLE
"Cannot create pull request without remote branch"

### ISSUE THREAD

**Issue by jackfranklin** [KnisterPeter/vscode-github#114]
Hey, 

I'm seeing the above error when trying to create a pull request. I've confirmed that the branch is on GitHub correctly and the plugin does seem to know that it's a GitHub based remote - if I use this plugin to browse Github it correctly takes me to the right place.

I've set up my token correctly + given it the repo access rights it needs, so I'm a bit stuck now. Any help would be much appreciated :)

<img width="903" alt="screen shot 2017-06-07 at 10 14 40" src="https://user-images.githubusercontent.com/193238/26871240-71071308-4b6a-11e7-931a-539996fc043c.png">

**Comment by KnisterPeter** [comment]
Hi,

sorry for late reply. Does the PR branch has the same name as the local branch?
Can you please add the log output of `git log --format=%b -n 1`  here?

**Comment by KnisterPeter** [comment]
The above screen is kind of missleading and there may be two issues involved here.
First the `git log..` cmd is executed to get the pull request body. This would mean there is already a remote branch found.  
Second the 'Cannot create pull...' is shown when no remote tracking branch was found. This might be the real issue here. Did you create your branch as remote tracking branch? Whats the content of your `.git/config` file? That might help track down this bug.

**Comment by KnisterPeter** [comment]
Also please update to vesion 0.16.2 and post the 'GitHub' output channel stacktrace here. This will help me a lot.

**Comment by KnisterPeter** [comment]
Closing since no answer for 7 days.
Feel free to comment here if the issue persists.

**Comment by jackfranklin** [comment]
Hey, I'm really sorry I was so slow to get back to you. I've just updated everything + will try this next time I make a PR and report back.

**Comment by mlavandero** [comment]
Hi, I am having the same issue.  I juste installed the extension and can use most of the commands, except the `Create Pull Request`.

At first I had the `git log` error, but now it stopped appearing.  The output of the 'GitHub' channel is empty the `.git/config` of the repo is:

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[branch "master"]
[remote "origin"]
        url = git@github.com:LemontechSA/cookbooks.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "develop"]
        remote = origin
        merge = refs/heads/develop
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "remove-the-admin-cookbook"]
        remote = origin
        merge = refs/heads/remove-the-admin-cookbook
```

The branch I'm trying to create a PR for is `remove-the-admin-cookbook`

**Comment by KnisterPeter** [comment]
@mlavandero Did you push your local branch before trying to create a pull request? This is currently a requirement, since the extension does not 'secretly' pushes your branch to github.

**Comment by KnisterPeter** [comment]
@mlavandero Can you please paste the output of the command `git log --format=%b -n 1` here? It would greatly help to track down the issue.

**Comment by mlavandero** [comment]
Answering both questions:

1. Yes, I did push my local branch
2. The output of `git log --format=%b -n 1` is empty, it only shows an empty line

Another thing I noticed in the developer tools is this error:
```
Command failed: git log --format=%b -n 1 
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I tried setting the `github.upstream` config with the upstream to the github repo, but it didn't work.

Another thing to consider is that I am working with a Repo inside an organization.

**Comment by KnisterPeter** [comment]
@mlavandero Thanks. Looks like a follow up error.
`git log --format=%b -n 1` should be executed with a commit hash appended. The commit hash of the first commit on that branch. For some reason the extension failed to get the commit hash. I'll add some more debug output and catch this one.

For better understanding? Do you have a master branch from which you started your feature branch? Are there already commits on the master or is this a 'fresh' repository?

**Comment by mlavandero** [comment]
Thanks @KnisterPeter.  The branch came from a master branch and it had at least one new commit.

**Comment by KnisterPeter** [comment]
@mlavandero I have another question, because I stumbled upon this error as well. When I tried to create a pull request I was on the master branch (and not as required on the feature branch). This results in the exact failures above. Are you able to confirm this? I would then guard the extension with a better error message if a user is on the default branch.

**Comment by jkettmann** [comment]
I just wanted to add a detailed message here and then realized: When I click the `Create PR` button on the bottom bar, I get this error message, but at the same time a select input to select the remote is opened. I never saw this input field, because it was kind of hidden by the error message

**Comment by KnisterPeter** [comment]
@jkettmann It is hard for me to track down this issue and I'm more than glad for any help.
Could you maybe create a small github repository with pull requests setup so I can try to inspect the problem there? Any more details are very welcome.

**Comment by KnisterPeter** [comment]
Fix released with 0.20.0

**Comment by lanwen** [comment]
Hit the same issue with this steps:

1. Commit to master locally
2. Switch to new branch and push to remote (with same name)
3. Try to create quick pull request from current branch

`git log --format=%b -n 1` in this case is empty

**Comment by KnisterPeter** [comment]
Right now you need to create the branch before committing. I think about a solution.

**Comment by jasonkuhrt** [comment]
> Right now you need to create the branch before committing. I think about a solution.

`hub` solves this with a `--push` flag on its `pull-request` command. Can we make a similar vscode config option for this extension?

**Comment by KnisterPeter** [comment]
Already have it (called `autoPublish`)
