### ISSUE TITLE
Error registering token

### ISSUE THREAD

**Issue by antonKrouglov** [KnisterPeter/vscode-github#115]
I have error "cannot read property 'connect' of undefined" when registering my github token. 
I am using latest VSCODE:
Version 1.12.2
Commit 19222cdc84ce72202478balcec5cb557b71163de
Date 2017-05-10T13:20:36.315Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by KnisterPeter** [comment]
I'll have a look into this. Seem to be a bug.
Are you using github.com or github enterprise?

**Comment by KnisterPeter** [comment]
Closing since no response for 7 days.

**Comment by daveerickson** [comment]
I am also getting the same error when trying to add my personal access token.
VSCode: 1.15.1
GitHub: 0.18.1

There is nothing in the GitHub channel in Output.

**Comment by KnisterPeter** [comment]
Does this still happens?

**Comment by daveerickson** [comment]
Interestingly no, it seems to register the token fine now. Same versions and everything.

**Comment by Confectrician** [comment]
I have the same error.
Tried a restart but that didn't change anything.

**Comment by KnisterPeter** [comment]
@Confectrician can you debug this error and post a stacktrace of it? The problem shouldn't exist anymore

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Confectrician** [comment]
Hey @KnisterPeter,

I started code with administrator access half an hour ago and it seemed to work then immediately.
Maybe that was the problem already?!

**Comment by MarlonRodriguez** [comment]
Why would you need admin access to use it?  That renders it a bit useless in an enterprise setting so it's still a bug.  There is no output in the console btw.  Only that error comes up.

**Comment by KnisterPeter** [comment]
The is no need for the admin access. All requested information should be available with user/repo access

**Comment by Confectrician** [comment]
This was a misunderstanding.

I have started vs code as an administrator on Windows which solved the problem for me.
This has nothing to do with the token settings!

**Comment by KnisterPeter** [comment]
Thanks for clearification. I think this could be closed then?

**Comment by Confectrician** [comment]
For my case yes.
I think none of the other posters here has still problems.
