### ISSUE TITLE
command 'vscode-github.setGitHubToken' not found

### ISSUE THREAD

**Issue by ringods** [KnisterPeter/vscode-github#122]
Hello,

Installed VSCode 1.13.0 yesterday and installed your GitHub extension (0.16.2) today. I generated a personal access token, but when I execute the command to set it in VSCode, I get an error at the top saying:

`command 'vscode-github.setGitHubToken' not found`

What am I missing?

Running on MacOS Sierra 10.12.5

**Comment by KnisterPeter** [comment]
Do you opened a workspace with a '.git' folder?
And if possible please open the output panel and paste the log output of the GitHub extension here (if any).

**Comment by ringods** [comment]
I'm not sure what project was open when I tried to execute the access token command. I just retried with a git project open and now it works.

Question: is the access token now stored for the complete use of the extension, or only for the project I have open now?

**Comment by KnisterPeter** [comment]
The token is stored globally.

**Comment by ranjit009** [comment]
You can configure the VS Code to your Github account is by opening a .git folder in the VScode.

**Comment by ranjit009** [comment]
Once you do it its registered across all the .git folders you have.

**Comment by KnisterPeter** [comment]
@ranjit009 Thats what I meant by 'stored globally'.

**Comment by ranjit009** [comment]
@KnisterPeter Thanks!

**Comment by bently211** [comment]
i also need help

**Comment by KnisterPeter** [comment]
@bently211 Please describe what you tried until the error occurs.
