### ISSUE TITLE
Be able to make pull request to another branch other than master

### ISSUE THREAD

**Issue by moisesrodriguez** [KnisterPeter/vscode-github#125]
It would be great if there was an option to select to what branch you want to create the pull request to. Right now it default to the default branch `master` but I want to make a pull request to the branch `develop`

**Comment by KnisterPeter** [comment]
As a simple workaround until resolved you could try to set the default branch in your github settings to `develop`

**Comment by KnisterPeter** [comment]
Will be released with 0.17
