### ISSUE TITLE
Commands are not available if there is no .git folder

### ISSUE THREAD

**Issue by mcascone** [KnisterPeter/vscode-github#126]
I installed this extension to VSCode, and get this error:
```command 'vscode-github.setGitHubToken' not found```
![capture](https://user-images.githubusercontent.com/8335079/27341519-1bcfc6e4-55a3-11e7-9673-4b0b652541cd.PNG)

There is no output in the Output, Problems, Debug Console, or Terminal.

**Comment by KnisterPeter** [comment]
Currently this happens if there is not `.git`  folder in your project or no folder open at all.

**Comment by KnisterPeter** [comment]
Will be released with 0.17
