### ISSUE TITLE
ENOENT and other missing docs on 'new pull request' ?

### ISSUE THREAD

**Issue by yeled** [KnisterPeter/vscode-github#134]
When using `code-insiders` I get this error: 

![](http://spodder-com-photo.s3.amazonaws.com/screenshots/ENOENT.png)

output from GitHub channel is only:

```
Create pull request on branch ansible-init
First commit on branch 1098e0ac
```

The problem was that I had set (it errored previously about this missing setting) git `core.editor` to "code -nw" which maybe didn't exist in the environment that the vscode-github was using (it's an alias in my shell to code-insiders).

Anyway once I set `core.editor` to `code-insiders` only I now get this: ![](http://spodder-com-photo.s3.amazonaws.com/screenshots/PR_EDITMSG__network__2017-07-11_11-30-03.png)

Which is better.. but I don't really understand. Should this template have been filled out already by vscode-github?

**Comment by KnisterPeter** [comment]
Currently it is assumed that you open your project file at the same level as your `.git` folder is. This is right now the project root.
And git will create the `PR_EDITMSG` file there which could be edited and used as pull-request messages afterwards.

**Comment by yeled** [comment]
Ok. I'm not sure that was the issue though. I am using an open editor based on where the `.git` folder is, and even if I then edit PR_EDITMSG, nothing happens. 

How can I get more debug logs?

**Comment by KnisterPeter** [comment]
I'll have to add more debug log for investigation.
You could fork the extension open it in github and then set a breakpoint and start debugging if you really like to get your hands dirty. :smiley:

**Comment by KnisterPeter** [comment]
Can you please tell me in which cases you get this error?
I have no clue what the file `PR_EDITMSG`  is for. The pull-requests by this extension are created using the github REST API. There is no need for a file-template to be filled.

**Comment by yeled** [comment]
It's been a really long time now since I came across this (I stopped using vscode mostly).

We can close it due to stagnation
