### ISSUE TITLE
Give correct error message if no access token is available

### ISSUE THREAD

**Issue by ButuzGOL** [KnisterPeter/vscode-github#136]
Always getting on create pull request getting
command 'vscode-github.createSimplePullRequest' not found
and then i 
1. go to add access token
2. press Esc 
and it works

**Comment by KnisterPeter** [comment]
This is strange. What version of vscode and vscode-github do you use?

**Comment by ButuzGOL** [comment]
vscode 1.14.0 (1.14.0)
vscode-github 0.17.0

**Comment by KnisterPeter** [comment]
Thats strange. Both commands are part of the extension.
Did you open a workspace and do you have an existing git project in it?

**Comment by ButuzGOL** [comment]
yes
the strange case after 
> set personal access token and press esc
it starts working

**Comment by KnisterPeter** [comment]
Currently either `set access token` or a `.git` folder should enable the extension.
I'll have to check if this is the case currently.
