### ISSUE TITLE
Feature Request: Click the toolbar link to open the GitHub PR page in your browser

### ISSUE THREAD

**Issue by cr3ative** [KnisterPeter/vscode-github#140]
Hi there! Love this extension. It would be wonderful to be able to set this bit of the toolbar:

<img width="193" alt="screen shot 2017-07-27 at 11 22 58" src="https://user-images.githubusercontent.com/1850718/28666109-f3610244-72bd-11e7-95e6-fbe3d3b965d2.png">

To open the current GitHub PR page in your default browser.

**Comment by KnisterPeter** [comment]
Hi, right now this is already connected to the `merge command`.
So this would be a breaking change.

**Comment by borekb** [comment]
This would be my first piece of feedback as well after trying the (awesome!) extension for 5 minutes.

It doesn't need to be a breaking change, clicking at the status bar could just open a list with multiple commands, e.g.:

![image](https://user-images.githubusercontent.com/101152/29932693-3f951eb6-8e75-11e7-8cbd-0ea3ecc4c984.png)

**Comment by KnisterPeter** [comment]
You are right. Adding more options would probably be possible. Good point

**Comment by KnisterPeter** [comment]
I've implemented this by allowing to override the status bar command.
This could be done setting the `github.statusBarCommand` configuration value. I think it is more comprehensible that mixing commands inside another one (merge and browse).

**Comment by borekb** [comment]
Nice, that will work for me very well. Just as a note, [Git Lens puts a lot of different things into the command bar](https://raw.githubusercontent.com/eamodio/vscode-gitlens/master/images/screenshot-commit-details.png) and I find it pleasant to use. (It's a bit of an extreme example though.)

**Comment by KnisterPeter** [comment]
I use `GitLens`  as well :smile:
