### ISSUE TITLE
command 'vscode-github.setGitHubToken' not found

### ISSUE THREAD

**Issue by bernardw1** [KnisterPeter/vscode-github#141]
I am probably doing something stupid as I have not really done much in VSCode or in GitHub. But when I press Ctrl+Shift+P and select the command ">Github: set personal access token" I get the error message "command 'vscode-github.setGitHubToken' not found"

any assistance with this would be appreciated.

**Comment by KnisterPeter** [comment]
What version of `vscode-github` are you using? With 0.17.2 this should be solved.

**Comment by bernardw1** [comment]
I am using 0.17.2

I will say that I really don't have much experience with Git or VSCode. So I may be doing something wrong,

I did just try it again (after setting up GIT within VSCode) and it is now working. I guess it needs the GIT features setup and working before trying to setup the GitHub extension.

**Comment by grapho** [comment]
I am having this issue as well... i am on version 0.22.0

I have GIT enabled by default (it is built-in to vscode)

There is no command found for: `vscode-github.setGitHubToken` even after restarting multiple times?

**Comment by KnisterPeter** [comment]
The buildin git is only a wrapper for the git binary for the OS you are using. Please make sure git is installed in your environment and working.
If you open your project folder in a terminal and it is possible to run `git fetch`  then it should work inside of vscode and the github extension.

**Comment by bipolarmorgan** [comment]
I'm having the same issue and git is installed...please advise
