### ISSUE TITLE
Cannot checkout pull request.

### ISSUE THREAD

**Issue by dlech** [KnisterPeter/vscode-github#143]
I am trying to checkout a pull request using the "GitHub: Checkout open pull request..." command.

When I run the command and select a PR, I get the following error message:

![selection_015](https://user-images.githubusercontent.com/963645/28889759-af545f52-778a-11e7-9a0c-339106510496.png)

The git log is...

```
git fetch
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...ev3dev/master
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git checkout -q patch-1
error: pathspec 'patch-1' did not match any file(s) known to git.
```

I suspect the problem is that I don't have a remote that corresponds to the PR author's repo. I would expect this extension to take care of adding the remote, for me.

**Comment by KnisterPeter** [comment]
Hi,
the extension does not add anything to your git settings right now. The git log output is from the `git` output panel? The output panel of this extension is called `github`.

But you are probably right with the error. You need to have a correct remote configured.

**Comment by KnisterPeter** [comment]
Can you give a bit more info on this? How could you checkout/browse pull-requests without proper setup of the git config (e.g. a remote)?

**Comment by dlech** [comment]
Checking out pull request works like this:

```
git checkout -b WasabiFan-screenshot-command master
git pull https://github.com/WasabiFan/vscode-ev3dev-browser.git screenshot-command
```

Browsing pull requests can be done via the GitHub API.

https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by KnisterPeter** [comment]
@dlech I still try to get the propper idea of your request.
Is the below process correct, or do you have something else in mind?

1. open vscode
1. use the extension to clone (checkout) a project (optional)
1. checkout a pull request

There is no fork involved in the process, right?

**Comment by KnisterPeter** [comment]
Closed since this is a stale issue. Feel free to reopen if required.
