### ISSUE TITLE
Unable to create a pull request

### ISSUE THREAD

**Issue by pinny13** [KnisterPeter/vscode-github#154]
Getting this error when running `Create pull request from current branch in current repository (quick)`

![image](https://user-images.githubusercontent.com/1291392/29339857-2329fa4a-81d1-11e7-9b5a-426883a50e0e.png)

I made a change, pushed, published, everything I could do is done and I verified that I can see the change in the remote branch.

And If I try to run `Create pull request...` I get this error

![image](https://user-images.githubusercontent.com/1291392/29339927-7aa78526-81d1-11e7-8cf4-f58159b0576a.png)

Any suggestions? Or any additional info I can provide to help with this issue?
Thanks

**Comment by KnisterPeter** [comment]
Hi,

do you have a github project with a correct remote already setup? Do you have a puhsed feature branch available? By that I mean you need to push your branch to github upfront.

The error message could be way better.

**Comment by pinny13** [comment]
So if I understand it correctly, it is basically looking for a remote branch in github and not finding it, and so it complains about the undefined part. 
Does anyone know if I can specify the url for the remote branch I am trying to commit to?

**Comment by KnisterPeter** [comment]
Yes right, you need the remote branch. But I do not get what you mean by 'url for the location'? Normaly you would fork a github project, clone the fork, create a feature/fix branch and push it to your fork. The create a pull-request based on that.

Besides forking and cloning all the above is possible with vscode and this extensions.

**Comment by pinny13** [comment]
Ok. Thanks.
