### ISSUE TITLE
Feature request: Support non-https GitHub enterprise

### ISSUE THREAD

**Issue by enure** [KnisterPeter/vscode-github#158]
Github enterprise may run on http rather than https. Currently https appears to be hard-coded into the extension. It would be nice if this was configurable, or if it read the protocol from the project's git config.

**Comment by KnisterPeter** [comment]
It should already be possible. When you setup the access token for your github instance you could provice the hostname like this: `http://your-domain/`.
This will allow to use http as protocol.

**Comment by enure** [comment]
I re-installed the extension and tried it again, and it's still not working.

The error, with my info redacted is:
> request to https://<hostname>/api/v3/repos/<user-name>/<repository>/issues?sort=updated&direction=desc failed, reason: connect ECONNREFUSED <ip-address>:443

I'll see if I can figure out how to debug this extension locally.

**Comment by enure** [comment]
For me, the bug is here:
https://github.com/KnisterPeter/vscode-github/blob/master/src/github-manager.ts#L50

When debugging locally, the hostname does not include the protocol, therefore `hostname.startsWith('http')` is always false.

The hostname variable is set on L46 (https://github.com/KnisterPeter/vscode-github/blob/master/src/github-manager.ts#L46), where it calls `git.getGitHubHostname`, which eventually calls `git.getGitHubOwnerAndRepositoryFromHttpUrl`, which returns the owner name and the hostname (without the protocol).

**Comment by KnisterPeter** [comment]
Thanks for debugging. I'll look into it for a fix.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KnisterPeter** [comment]
Will be released with 0.20.0
