### ISSUE TITLE
Setup GitHub Enterprise Token command not found

### ISSUE THREAD

**Issue by jonnyyu** [KnisterPeter/vscode-github#203]
using v0.20.1,

GitHub: Setup GitHub Enterprise Token now shows command 'vscode-github.setGitHubEnterpriseToken' not found.

v0.19.0 is good.

**Comment by jonnyyu** [comment]
break by this 9f5bda199ffb01dccd2eff3c349a8dd5177f5e26

**Comment by KnisterPeter** [comment]
Thanks for reporting. I'll fix this regression as soon as possible.

**Comment by jonnyyu** [comment]
Thanks for fixing it so quickly!
