### ISSUE TITLE
Error spawn git ENOENT returned when entering Personal Access Token

### ISSUE THREAD

**Issue by ricardofreeman** [KnisterPeter/vscode-github#207]
Hi, what could be the reason for this error when providing the Personal Access Token?
![error_git](https://user-images.githubusercontent.com/17456791/31008397-e80907dc-a4fb-11e7-9fc2-41b1487b073e.gif)
Thanks in advance.

**Comment by KnisterPeter** [comment]
Do you have git installed?
This error means it is not possible to execute the git command in the background.
This is the case if either there is no git executable or it is not found in you OS executable search path (e.g. $PATH on linux/unix)

**Comment by ricardofreeman** [comment]
Thanks for your quick response @KnisterPeter 
I only had GitHub installed. After your comment I installed git and the command is now available in the path, it's recognized anywhere in the command line. I can run a `git status` in the command line inside this project's folder and I get the status.
Sadly the problem persists, am I missing something?
Thanks

**Comment by KnisterPeter** [comment]
Did you restart vscode? Not only run a `reload` command but really quit and restart vscode.
I hope that helps.

**Comment by ricardofreeman** [comment]
* I tried disabling the other extensions I installed to open the current file on Github (what I'm looking for) and closed VSCode. When I opened it I was able to enter the Token and it worked on that window. 
* Then I tried with another project and it looked like the token was not registered. When I tried to enter it again I got the same error.
* I closed VSCode and opened again on the first project that was already working and I got the same error.
![error_git2](https://user-images.githubusercontent.com/17456791/31016605-502897d0-a51d-11e7-9741-ee27f878c945.gif)
Perhaps I'm missing some requirement.
I'm happy to send you any logs you might need to debug this.
Thanks

**Comment by KnisterPeter** [comment]
I need to prepare some more logging inside of the extension. So this might need some time.
I'll flag this as bug and report back as soon as I could get into more detail. Thanks for any help.

**Comment by KnisterPeter** [comment]
I've released 0.21 which logs all local git commands to the `GitHub` output channel.
Also it is possible now to set the `gitCommand` setting in your configuration which should point to your git executable (if nothing else helps).

Please test and report back any issues.

**Comment by ricardofreeman** [comment]
Not sure if it has any relation to the latest changes but it's working already, thank you!
