### ISSUE TITLE
Token authorization - error occurs

### ISSUE THREAD

**Issue by BitYog** [KnisterPeter/vscode-github#221]
I set up the extension with my token. There was an error message: "no vscode.workspace.workspaceFolders". How do I work around this?

**Comment by KnisterPeter** [comment]
What version of vscode do you use?
The `vscode.workspace.workspaceFolders` are part of the latest version. If you are using these this error may be triggered by not having an open project folder.

**Comment by BitYog** [comment]
The version I am using is 1.15.1

**Comment by BitYog** [comment]
@KnisterPeter Now the error shown is "Command failed: git config --local --get remote.origin.url"

**Comment by BitYog** [comment]
This happened after I opened a project folder.

**Comment by KnisterPeter** [comment]
Do you have git executable installed and in your executable path?

**Comment by KnisterPeter** [comment]
Closed because of no response. Feel free to reopen if needed.
