### ISSUE TITLE
Feature request: list target branches as quickpick when creating pull request

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/vscode-github#223]
For a simplifed UX it would be great to list all known branches (local and remote) as QuickPick instead of only allow input of target branch name.

@KingHenne

**Comment by KingHenne** [comment]
Yes, QuickPick would be perfect! 👌🏻

**Comment by KingHenne** [comment]
🎉 Awesome, I just tested it and it worked perfectly! Thanks for the quick implementation! 🐎
