### ISSUE TITLE
Feature Request: Clicking on pull-request in status bar opens github

### ISSUE THREAD

**Issue by ProLoser** [KnisterPeter/vscode-github#242]
I frequently want to review pull-requests through the GitHub interface. Is there a chance you could add an option to the list of actions to simply go to GitHub?

Frankly, I feel this should be the default behavior because I do not endorse making destructive changes (merging) through a status bar extension (outside the context of the full diff), but at the very least just having a simple way to open the web page would be an improvement.

**Comment by KnisterPeter** [comment]
This should already be possible.
You can configure the status bar command by setting `github.statusBarCommand` to `vscode-github.browserSimplePullRequest`.
