### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by cmalard** [KnisterPeter/vscode-github#249]
Hello there,

No idea what's going on, I configured my Github token but I can't use this extension:
```
git config --local --get remote.origin.url
Not Found
Error: Not Found
	at Object.<anonymous> (/home/cedric/.vscode/extensions/KnisterPeter.vscode-github-0.22.0/out/src/provider/github/index.js:84:23)
	at Generator.next (<anonymous>)
	at fulfilled (/home/cedric/.vscode/extensions/KnisterPeter.vscode-github-0.22.0/out/src/provider/github/index.js:13:58)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)
```
If I run the command in my terminal: no problem.

**Comment by KnisterPeter** [comment]
Do you have a working git installation on your computer? By that I mean does it work if you open a terminal and type `git status` in your project working directory?
Otherwise you may need to set `github.gitCommand` in your settings to point to your git executable.

**Comment by cmalard** [comment]
Hi @KnisterPeter :-)
- It totally works in my terminal
- I'm using Git Lens extension perfectly
- I can run git commands from VSCode terminal

And I'm not sur vscode-github has access to git, here is my full log:
```
Visual Studio Code GitHub Extension
git --version
git config --local --get remote.origin.url
git config --local --get remote.origin.url
Connected with provider GitHub Client
git branch
git config --local --get remote.origin.url
git config --local --get remote.origin.url
Not Found
Error: Not Found
	at Object.<anonymous> (/home/cedric/.vscode/extensions/KnisterPeter.vscode-github-0.22.0/out/src/provider/github/index.js:85:23)
	at Generator.next (<anonymous>)
	at fulfilled (/home/cedric/.vscode/extensions/KnisterPeter.vscode-github-0.22.0/out/src/provider/github/index.js:13:58)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)
git branch
git config --local --get remote.origin.url
git branch
git config --local --get remote.origin.url
git branch
git config --local --get remote.origin.url
...
```

Nothing changes with `github.gitCommand` set. Any idea? Do you need me to create & provide more logs?

**Comment by KnisterPeter** [comment]
Okay, provided the logs you give here already I can only assume that the remove url of your git project may not exist.
Do you use github.com or is it github enterprise hosted on a custom domain?

**Comment by cmalard** [comment]
Ok, got it !
I was too restrictive on the access for the token:
![screen](https://user-images.githubusercontent.com/1692136/31882952-ac3c7162-b7e8-11e7-9e34-1b50b2252bf3.png)

Once I checked `repo`, it solves the problem.
It may be the only way to include organizations private repos access.

Thanks for your time @KnisterPeter

**Comment by cmalard** [comment]
What do you think of adding some tip about this in the error ?
Like : `Not Found - check that your token configuration has "repo" checked`

**Comment by KnisterPeter** [comment]
I've already opened an isssue to improve setup.
I've add this as reference. Great it does work now. And every feedback is welcome. :rocket: 

Link to #250

**Comment by cmalard** [comment]
Great ! I close this one ;-)
