### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by bsvipas** [KnisterPeter/vscode-github#255]
Hi,

I suggest to remove status bar coloring for `none` and `githubPullRequestIcon`. Because it's impossible to colorize them in theme which is bad.

**How it looks:**
![image](https://user-images.githubusercontent.com/30043375/32158509-b94e166c-bd51-11e7-8dfe-b6b90d00a0cc.png)

**How it needs to look like:**
![image](https://user-images.githubusercontent.com/30043375/32158503-ad1f359c-bd51-11e7-88a2-5ae48aac407d.png)

Thanks!

**Comment by KnisterPeter** [comment]
You can already do so.

**Comment by bsvipas** [comment]
@KnisterPeter How? Because I found it's hardcoded inside `src` of your extension.

**Comment by KnisterPeter** [comment]
See #202

**Comment by bsvipas** [comment]
@KnisterPeter `"github.statusbar.color": false` still color is white for me.

**Comment by KnisterPeter** [comment]
I never set a color if status bar color is false. So it is the default as vscode handles it.

**Comment by bsvipas** [comment]
Issue still exists. `"github.statusbar.color": false` works, but if I change files it becomes white again... Just try to change between opened files also include some Untitled and you will see.

**Comment by borekb** [comment]
I'm also seeing strange statusbar behavior, for example, this is what I see now:

![image](https://user-images.githubusercontent.com/101152/32213750-cbfe8bae-be1c-11e7-9080-8cdb2425ef49.png)

While my settings are:

```
"github.statusbar.command": "vscode-github.checkoutPullRequests",
"github.statusbar.color": false,
"github.statusbar.successText": "PR #${prNumber}",
"github.statusbar.failureText": "PR #${prNumber} (checks failing)"
```

It looks like _sometimes_, the settings are not picked up. (Some other times, the status bar behaves exactly like configured.) I'm on VSCode 1.17.2 and GitHub extension v0.23.0.

**Comment by KnisterPeter** [comment]
I'll look into it

**Comment by borekb** [comment]
Thanks. Another piece of info: right now, the status bar is not showing at all:

![image](https://user-images.githubusercontent.com/101152/32213993-b7f1169e-be1d-11e7-832e-3c2b9df2a1ec.png)

(The "OUTPUT" panel is set to "GitHub".)

**Comment by borekb** [comment]
Right now, everything is OK. My wild theory is that multiple things inside VSCode try to use Git and it somehow gets stuck. Those three piece in my case might be:

1. VSCode itself (periodic checks for the SCM provider)
2. GitLens extension
3. GitHub extension

Right now, I can see many log messages in GitHub's extension output panel, previously, it was stuck at just `git --version` and that was it.

**Comment by KnisterPeter** [comment]
0.23 did improve a lot in that place. Right now there is more logging. I'll hide it behind debug mode in the future.

**Comment by KnisterPeter** [comment]
Thx for all the information.

**Comment by KnisterPeter** [comment]
One possible problem leading to 'stuck' status bar state may be that an active editor is required (open file).
This is because of multi folder support to determine which workspace folders status need to be shown.

**Comment by KnisterPeter** [comment]
@borekb @bsvipas  Is this issue still occuring, or did the last update help?

**Comment by borekb** [comment]
I haven't seen the issue recently.

**Comment by KnisterPeter** [comment]
I'll close it for now. Please report back if it occurs again.
