### ISSUE TITLE
A lot of network traffic

### ISSUE THREAD

**Issue by borekb** [KnisterPeter/vscode-github#256]
I've opened the Output panel of this extension and remote requests to GitHub API are going out all the time – it looks like very two seconds, 5-10 requests are sent. This feels way too much. I understand that this is to ensure fresh data but still, I wouldn't expect such heavy traffic. Maybe an option would be to fetch some data only when they are needed, even at the expense of slightly slower reaction?

**Comment by KnisterPeter** [comment]
You can configure the status update `github.statusbar.refresh`.
This issues the most traffic. All other calls are responded by github with 304 and no body.
That means a request but no payload.
Feel free to reduce status refreshes.
