### ISSUE TITLE
Github checkout pull request doesn't work for contributions

### ISSUE THREAD

**Issue by grobie** [KnisterPeter/vscode-github#258]
Thanks for the work on this extension! I'm an open-source maintainer and have to review many pull requests. I had hoped this extension would help me to checkout PRs opened by contributors. These contributors don't have git write access to the repos and open the PRs from their forked repository

`Error: Git: pathspec 'feature/foobar' did not match any file(s) known to git.`

In the git log I can see it tries to checkout that branch from my local repo:

```
git checkout -q feature/foobar
error: pathspec 'feature/foobar' did not match any file(s) known to git.
```

In the command line instructions shows at the bottom of each pull request, it suggests the following git commans:

```
git checkout -b somecontributor-feature/foobar master
git pull https://github.com/somecontributor/prometheus.git feature/foobar
```

Would it be possible to add support to checkout contributor PRs?

**Comment by KnisterPeter** [comment]
Nice idea

**Comment by cdeil** [comment]
+1, support to fetch branches from Github forks and check out PRs from contributors would be super useful for me.

**Comment by KnisterPeter** [comment]
@grobie This is implemented now and contained in the next release. Be aware that pulling external code could be harmful and need to be confirmed.

**Comment by edouard-lopez** [comment]
I'm still not able to checkout pull request:

```
> git checkout -q instance_connection
error: pathspec 'instance_connection' did not match any file(s) known to git.
```

### Extension information:

> Name: GitHub
> Id: knisterpeter.vscode-github
> Description: Integrates github and its workflows into vscode
> Version: **0.30.2**
> Publisher: KnisterPeter
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github

**Comment by KnisterPeter** [comment]
@edouard-lopez Do you have an example repository? The implementation checks if the selected pull request differ in the repository url of the source and then checkout that remote repository.

**Comment by edouard-lopez** [comment]
With an open source repo ([`pure`](https://github.com/rafaelrinaldi/)) it succeed to pull https://github.com/rafaelrinaldi/pure/pull/169.

But still fail with private repo.

**Comment by KnisterPeter** [comment]
@edouard-lopez I'm not sure where's the difference between public and private repos. Is the private on in github enterprise? I think it's maybe not be available in the list of pull requests? I have no private repositories so I cannot test this without your help.

**Comment by edouard-lopez** [comment]
To my knowledge, the repo is not part of a Github Enterprise. But private repo might require authentication.

You can create `private` repository it's [part of the free plan](https://github.com/pricing#feature-comparison).

I create a [private repo with a PR](https://github.com/edouard-lopez/vscode-github-private-pr). I have no issue, but I'm the owner, so I'm adding you as a collaborator in order to try to replicate. The PR to fetch is:

> commit on pull request on private repo #1

**Comment by KnisterPeter** [comment]
@edouard-lopez `edouard-lopez/vscode-github-private-pr` will result in a 404 error. I cannot see the repository.

**Comment by edouard-lopez** [comment]
@KnisterPeter my bad, forgot to add you. It's done
