### ISSUE TITLE
GitHub error: Validation Failed

### ISSUE THREAD

**Issue by tomitrescak** [KnisterPeter/vscode-github#275]
Hi thanks for this amazing extension!

 I'm getting this error "GitHub error: Validation Failed"

I am not sure what it means.
I have a new branch "feature/tests" in my repo, and I'm trying to create a pull request to master.

**Comment by tomitrescak** [comment]
Nevermind: branches were identical. 

I guess the error comes from GitHub so there is not much that can be done to make it less cryptic.

**Comment by lxl5643** [comment]
22
