### ISSUE TITLE
GH Enterprise problem

### ISSUE THREAD

**Issue by marek-nogiec** [KnisterPeter/vscode-github#280]
When I try any command I get the following warning:
'Please setup your Github Personal Access Token and open a GitHub project in your workspace'

I've got both GitHub Enterprise and GitHub tokens set up using the extension command ('Set up GitHub Enterprise Token...') and got only one project open in the workspace which is on that GHE.

**Comment by KnisterPeter** [comment]
That may depend on the url of your git origin. Can you please post the URL (you can anonymize it if you like to) of your project?

**Comment by marek-nogiec** [comment]
@KnisterPeter git@github.mycompany.io:org-name/repo-name.git

**Comment by KnisterPeter** [comment]
I'll have a look as soon as possible.
