### ISSUE TITLE
Where do I enter my Personal Access Token?

### ISSUE THREAD

**Issue by timhaintz** [KnisterPeter/vscode-github#281]
Hello, just installed GitHub 0.24.1. I can't work out how to enter my Personal Access Token for GitHub. 
Marlon Copeland mentioned the same thing here:
https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github#review-details

Thanks, Tim.

**Comment by KnisterPeter** [comment]
If you open the command panel (`ctrl+shift+p`) and enter 'Access Token` you can input it in the dialog and then start using the other commands.

**Comment by timhaintz** [comment]
Thanks @KnisterPeter , I will do a PR and add this in to update your doco.
Thanks again.
Cheers, Tim.
