### ISSUE TITLE
Bug: Doesn't support remotes that aren't named "origin"

### ISSUE THREAD

**Issue by pzelnip** [KnisterPeter/vscode-github#286]
If I don't have a remote for the repo named "origin", then upon trying to open a pull request via the extension I get:

```
Error: Error: Command failed: git config --local --get remote.origin.url
```

I rename my ```origin``` remote to ```github``` on all Github repos I checkout.  I can work around the limitation by creating a remote called ```github``` and another duplicate remote called ```origin``` for my checked out copy, but that's kind of a pain.  I'd rather the extension just examines any remotes I have defined on a repo, and matches any that have ```github.com``` in the url.  Or alternatively, a workspace setting where I can tell it which remote to use (which I could see being useful if you for example fork a repo, clone your fork to your local machine, and then add a remote entry for the repo you forked from in addition to the remote for your fork).

**Comment by KnisterPeter** [comment]
There is already the setting `github.remoteName` which solves exactly your purpose.
It default to 'origin'.
But besides that the remotes should be examined as well. So I'll keep this open for reference, okay?

**Comment by pzelnip** [comment]
You sir, are awesome, that's *exactly* what I was looking for.  Feel free to keep this open if you wish (I don't see any reason to), I've put up a PR with some tweaks to the README to make this setting a bit more evident.
