### ISSUE TITLE
Strange interaction with All in One Markdown extension – Enter not working

### ISSUE THREAD

**Issue by borekb** [KnisterPeter/vscode-github#298]
The Enter key wasn't working for me when editing Markdown documents and I'm a user of the All in One Markdown extension so I first discussed the possible issue there: https://github.com/neilsustc/vscode-markdown/issues/17. However, it turns out that the GitHub extension is causing the issue somehow – I'm not sure how but when I disable it all is OK.

Looking further into it, the GitHub extension has some sort of problem with the repo of my current project. When I click on the status bar icon which is configured to offer a list of open pull requests, it's spinning for a very long time (~2 minutes) and then says "there are no items to choose from".

Also with pressing Enter in the Markdown, I see this in the DevTools:

```
mainThreadExtensionService.ts:44 FetchError: request to https://api.github.com/user/repos failed, reason: socket hang up
	at ClientRequest.<anonymous> (C:\Users\borek\.vscode\extensions\KnisterPeter.vscode-github-0.26.0\node_modules\node-fetch\index.js:133:11)
	at emitOne (events.js:96:13)
	at ClientRequest.emit (events.js:191:7)
	at TLSSocket.socketOnEnd (_http_client.js:394:9)
	at emitNone (events.js:91:20)
	at TLSSocket.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e.invoke @ abstractThreadService.ts:42
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

I'm not sure what is wrong with my repo, it is similar to my other repos which work fine, and even if there was some Git problem, I'm not sure why it would affect pressing Enter in Markdown..

**Comment by borekb** [comment]
All the Git operations are heavily affected, for example, the Git / SCM sidebar doesn't show any changes for a very long time (1 minute or more). After disabling the GitHub extension, everything is back to normal.

Some info about the repo:

- It's a private one (but I have other private repos that work fine).
- It has zero open pull requests and just the `master` branch.

**Comment by KnisterPeter** [comment]
Thats strange. I'm not messing with the keyhandling in any way.
Maybe its the HoverProvider which searches open documents for comments like this '#123' and will link them to the related github issue.
I'll dig a bit deeper later on.

**Comment by borekb** [comment]
Another error message that I got is `TextEditor(vs.editor.ICodeEditor:1,$model2) has been disposed`. This is my configuration:

VS Code version: Code - Insiders 1.20.0-insider (757ff83f0dece1ecf43d3a92e91fe467de1cc9dc, 2018-01-29T05:13:39.772Z)
OS version: Windows_NT x64 10.0.16299

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.26.0
markdown-all-in-one|yzh|1.0.4

**Comment by KnisterPeter** [comment]
I've installed the markdown extension as well and everything works as expected.
Maybe there is something else different on your github project. I'm a bit concerned about the slow response times.
There is a part of this extension which provides hovers and tooltips in any document (source and markdown) which looks like this `#123` (hash followed by any number) and links it to the github issue or pull request.
I think that might influence with the markdown extension but its all public vscode api and should work in the background not interfering with other extensions.

Without some more detail about your project I'm not able to dig into the long response times. Can you probably clone the project a second time and just use this extension to see if it is faster?

**Comment by borekb** [comment]
I tried the clean clone but the issue is the same. It also seems to affect non-editor actions, for example, the SCM sidebar takes very long to detect a file change.

I can't share this very repo but I'll try to come up with a similar one that still reproduces the issue.

**Comment by KnisterPeter** [comment]
That would be a great help. Maybe `code --status` could help to show the cpu usage of a specific process.

**Comment by KnisterPeter** [comment]
This topic and the ones below may help debugging to get a few more information:
https://code.visualstudio.com/updates/v1_19#_status-command-line-option

**Comment by borekb** [comment]
Will do (hopefully tonight, time is tight now).

**Comment by KnisterPeter** [comment]
Closed, because no additional info given. Please feel free to reopen if required.
