### ISSUE TITLE
command 'git.clone' not found

### ISSUE THREAD

**Issue by LePandaFou77** [KnisterPeter/vscode-github#299]
Hey !

I have download your "GitHub" in vscode.

I can not do "git Clone"
![image](https://user-images.githubusercontent.com/32986674/35530232-ca467a5c-0533-11e8-96bb-aa019582f935.png)

**Comment by KnisterPeter** [comment]
There is no `clone` command in the vscode extension. This command is provieded by the git extension in vscode. Please report there.
