### ISSUE TITLE
status bar color

### ISSUE THREAD

**Issue by bsvipas** [KnisterPeter/vscode-github#301]
Hi,

`"github.statusbar.color": false` but still, it's with colors.

![image](https://user-images.githubusercontent.com/30043375/35614725-b3c9100a-0678-11e8-9edb-5381fb0632b2.png)
![image](https://user-images.githubusercontent.com/30043375/35614713-ad5a260a-0678-11e8-93cd-b613acf4f793.png)

VS Code: 1.20.0 Insiders (latest)
OS: macOS
This extension version: latest (0.26.0)

**Comment by KnisterPeter** [comment]
I'll look into it. Thanks for reporting.

**Comment by bsvipas** [comment]
@KnisterPeter The problem is here:

https://github.com/KnisterPeter/vscode-github/blob/2c48172e51fec0351e3051b2ccbad7276efc1e9e/src/status-bar-manager.ts#L11

Because it makes it to white. If color is false you should use the default color defined in user theme. Or you can don't setup color on initialization if it's false.

**Comment by KnisterPeter** [comment]
If colors is false it does not set the color code to none.
As you can see here the setters are guarded by a check: https://github.com/KnisterPeter/vscode-github/blob/2c48172e51fec0351e3051b2ccbad7276efc1e9e/src/status-bar-manager.ts#L92

**Comment by KnisterPeter** [comment]
But any PR is welcome

**Comment by bsvipas** [comment]
@KnisterPeter yeah you're right... Hm, so that's the problem then...

**Comment by maxim-lian** [comment]
Not sure whether another bug report is that helpful, but I'm seeing a couple of problems:

The color is still there:
![image](https://user-images.githubusercontent.com/5635139/38212366-85719f72-368b-11e8-81a7-c8e6d301350a.png)
![image](https://user-images.githubusercontent.com/5635139/38212487-e758a3fc-368b-11e8-825d-e17494c95514.png)


The ordering of the status bar changes, and the flicker between is fairly distracting:
![image](https://user-images.githubusercontent.com/5635139/38212464-d73fd85a-368b-11e8-81ef-7f205865ab37.png)

Let me know if any other info is helpful

**Comment by KnisterPeter** [comment]
@maxim-lian I'll have no clue why colors are still there. The status bar ordering should go into a new issue. Can you split that?
