### ISSUE TITLE
I have added my Access Key, but it still asks me to enter an access key

### ISSUE THREAD

**Issue by felipe1982** [KnisterPeter/vscode-github#302]
I have pasted in my Access Key, and tried to open a pull request, but it says I need to add my access key. I also tried removing all access keys, and trying again, restarting Code, but same problem. 
I am running Windows 10, latest Code, and downloaded this plugin from within Code itself.

**Comment by KnisterPeter** [comment]
Sorry for late response. Your personal access key need to have setup to allow repo access. Maybe thats a problem. Otherwise it would help to know how did you clone your project?
Any additional info may help as well.

**Comment by eduardonunesp** [comment]
Same problem here

![image](https://user-images.githubusercontent.com/582516/36323591-88991f16-1338-11e8-8d30-5e0ca74dbecf.png)

![image](https://user-images.githubusercontent.com/582516/36323599-9271fd1e-1338-11e8-9752-0ba654207fdf.png)

**Comment by KnisterPeter** [comment]
@felipe1982 @eduardonunesp 
Please try the command `Remove token...` to check if its really a github token which is available. The command lists all domains which are known tokens available.

As well, please give some information on how the project folder was created. E.g. what is the git-url? Is it https, git, ssh? Anything might help.

**Comment by KnisterPeter** [comment]
As well the output of the Github extensions there should be a line like this

    Connected with provider GitHub Client

Or if not some error response. Please paste the output of the log here.

**Comment by eduardonunesp** [comment]
Ok, looked in console found an error with my remote name, after removing and reading the key it worked

**Comment by KnisterPeter** [comment]
Glad to help
