### ISSUE TITLE
support github enterprise with self-signed certificate

### ISSUE THREAD

**Issue by lihuanshuai** [KnisterPeter/vscode-github#304]
My company use github enterprise with a self-signed certificate. Every time I want execute any commands of this extension to do some operation on github enterprise, it will throw 

```
Error: request to https://github.intra.example.com/api/v3/repos/huanshuai/repo failed, reason: self signed certificate in certificate chain
```

like error and failed.

I think it may be due to bug similar to bitinn/node-fetch#19, the solution could be creating a workspace config item for whether reject self-signed certificate or not. If the solution is ok, I could pr for this (maybe days) later

**Comment by KnisterPeter** [comment]
That would be okay for me. Please go on and create a PR.
I'll help with any questions and suggestions.

**Comment by lihuanshuai** [comment]
done
