### ISSUE TITLE
Proxy setting ignored?

### ISSUE THREAD

**Issue by chrs-myrs** [KnisterPeter/vscode-github#309]
All calls to the GitHub API time out, I suspect this is because it is not respecting the HTTP proxy settings from either vscode or git.  Accessing the same URL in a browser returns successfully.

**Comment by KnisterPeter** [comment]
Right, there is right now no support for proxys implemented.

**Comment by jmarandet** [comment]
Hi, I am not an expert, but I am issuing a same kind of proxy problem with a lot of certificate issue, and I suspect that the "pretend" client may be somehow involved in these troubles.

There is a quite good vscode plugin called Rest-Client ( https://github.com/Huachao/vscode-restclient ) that seems handy to me.
I don't know if it could help to found some inspiration @KnisterPeter ? or maybe build your plugin on the top of it, with an extension-dependency and calling its (good) methods ?

For example, when I read this code https://github.com/Huachao/vscode-restclient/blob/master/src/httpClient.ts I can see that it handles both proxies and certificates.
And when I launch it against our Github Enterprise api, it succeeds against the same URLs that the vscode-github plugin seems to fail against.

**Comment by KnisterPeter** [comment]
@jmarandet You are right. Its in pretend which right now gets no proxy settings. They should be added while setting up pretend (or the more low level http/https module).
