### ISSUE TITLE
Feature request: Show pull request from upstream too

### ISSUE THREAD

**Issue by Spy-Seth** [KnisterPeter/vscode-github#31]
In case we are working on a fork, the PR are mainly open on the upstream repository not on the origin repository. It will be nice to be able to browse them too with the extension.

**Comment by KnisterPeter** [comment]
Would it be okay to have a configuration setting to set upstream repo? It is quite hard to get all the information on every command from the user. And it would be very annoying.

**Comment by Spy-Seth** [comment]
> Would it be okay to have a configuration setting to set upstream repo?

It seems fine.

**Comment by KnisterPeter** [comment]
Released as 0.8.0
