### ISSUE TITLE
[Feature] Browse repositories

### ISSUE THREAD

**Issue by realappie** [KnisterPeter/vscode-github#333]
It would be awesome if we could browse repositories and clone them in the editor. I visit github.com a lot to figure out what a projects remote URL is.

**Comment by KnisterPeter** [comment]
@realappie Nice idea. I'll think about how to implement it.

**Comment by realappie** [comment]
@KnisterPeter Did you ever get to think about a possible implementation ? :)

**Comment by KnisterPeter** [comment]
@realappie Not until now. But the github apis allow this, so it is more or less a work effort.
You can create a PR if you want to.
