### ISSUE TITLE
Status bar ordering

### ISSUE THREAD

**Issue by maxim-lian** [KnisterPeter/vscode-github#336]
As per https://github.com/KnisterPeter/vscode-github/issues/301#issuecomment-378021462

The ordering of the item on the status bar is inconsistent. All the other items are consistently ordered except for this. 
This is a workspace with multiple repos.

https://user-images.githubusercontent.com/5635139/38212366-85719f72-368b-11e8-81a7-c8e6d301350a.png
https://user-images.githubusercontent.com/5635139/38212464-d73fd85a-368b-11e8-81ef-7f205865ab37.png

Thanks!

**Comment by KnisterPeter** [comment]
@maxim-lian Thanks. I'll take care of it

**Comment by KnisterPeter** [comment]
Will be released in 0.28
