### ISSUE TITLE
Pull request title incorrect

### ISSUE THREAD

**Issue by tomerMP** [KnisterPeter/vscode-github#338]
When creating a pull request the last commit message is taken as the PR title instead of the title I added during the "Create PR" process.
The title entered during the process is added to the PR as a comment and not a title

To recreate:

- Create branch
- Make change
- Commit and publish to remote
- Click "Create PR" button in VSCode
- Select repo
- Select branch to which PR will be created
- Add PR title
- Go to GitHub pull requests and see that the title is actually the commit message from the last commit made on branch instead of the title added in previous step

**Comment by KnisterPeter** [comment]
Thanks for reporting

**Comment by albireox** [comment]
I'm having the same issue, which causes the not ideal workflow of having to open the newly created PR to edit the title.

I think a good implementation would be that if `customPullRequestDescription="gitEditor"`, the first line of the message become the PR title and the rest become the description.

**Comment by tomerMP** [comment]
I disagree entirely.
Why would I want any part of a commit message to be the title of the PR?
I would suggest asking for the title at the time of PR creation and then simply using the title given by the user.
It would seem like you were almost there in the previous versions but then after an update the title request was just abandoned entirely.

**Comment by KnisterPeter** [comment]
The default (like in the github hub tool) should be (and is already) to use the first line of the first commit message of the pull request branch as title.
The bug here is that if a separate title is given, its not used.
I would not like to change the default in any other way.

**Comment by KnisterPeter** [comment]
And @albireox you are right for the `customPullRequestDescription="gitEditor"` that would be possible and sounds sane as it is aligned with the default behaviour.

**Comment by tomerMP** [comment]
I have no problem with the default, and I understand your reasoning behind what the bug is. But the ability to create a custom PR title would be great. So maybe it’s a “return a feature” request, and fix the bug that caused it not to work.

**Comment by RossValler** [comment]
I've created a potential solution to this here: https://github.com/KnisterPeter/vscode-github/pull/398

Implemented as a new feature rather than a change to the existing description.

**Comment by KnisterPeter** [comment]
Splitted the custom editor into #405
