### ISSUE TITLE
Error alert after PR

### ISSUE THREAD

**Issue by napa3um** [KnisterPeter/vscode-github#346]
![image](https://user-images.githubusercontent.com/665538/39006839-fc934680-440c-11e8-8c96-a138d9f8da6a.png)
 This notice show after PR (PR is worked, all is good, unnecessary this alert)

**Comment by KnisterPeter** [comment]
Thanks for reporting. I'll try to have a look at that.

**Comment by napa3um** [comment]
Additional info: PR to enterprise repository (may be this info is not relevant).

**Comment by KnisterPeter** [comment]
Its probably these lines of code leading to this error:
https://github.com/KnisterPeter/vscode-github/blob/feat/allow-token-update/src/provider/github/repository.ts#L104-L109

Need to inspect the PR creation result.
