### ISSUE TITLE
Extension generates lots of API calls against GitHub

### ISSUE THREAD

**Issue by larsxschneider** [KnisterPeter/vscode-github#356]
👋 @KnisterPeter !

It looks like as if `vscode-github` v0.27.1 generates a lot of API calls against GitHub in certain cases. Here are the counted API calls from a single VSCode user working on a single repo over a single day on my GitHub Enterprise instance:
```
32328 /api/v3/repos/demo-org/demo-repo
 9978 /api/v3/repos/demo-org/demo-repo/pulls/123
11174 /api/v3/repos/demo-org/demo-repo/pulls?state=open
```

That's >55k requests per day. IOW more than 2 requests per second in a 8h work day 😃 ! While github.com can probably handle this load just fine, this might be a problem for GitHub Enterprise users.

Do you have an idea what could cause the excessive API usage in the extension?

/cc @terrorobe @b4mboo

**Comment by KnisterPeter** [comment]
@larsxschneider Yes, its the statusbar updates which indicate build status of the current branch/pull request.
You could configure it via `github.statusbar.refresh`. Default is every 5 seconds one request.

**Comment by larsxschneider** [comment]
>  Default is every 5 seconds one request.

Thank you! That explains the [`pulls` API](https://developer.github.com/v3/pulls/#get-a-single-pull-request) calls. Do you have also an idea about the [repo API](https://developer.github.com/v3/repos/#get) calls?

**Comment by KnisterPeter** [comment]
@b4mboo Would be interesting but probably hard in the wild. Since there are NATed networks and firewalls. So webhooks will most likely fail. As well there is right now no 'server' which could receive the call. But I'm open to discuss this.

@larsxschneider These are probably created from the commands executed by the extension. Since right now the commands are kind of stateless, some call are fired every time again and again. But it shouldn't be a problem normally since the github caches are respected and the response (also for GHE) should be 304 as status code and the cache should be used.

**Comment by KnisterPeter** [comment]
@larsxschneider I will think about caching more agressivly and adding state to the REST client. That would reduce the traffic a lot. Can you please explain a bit more in detail why you require this? The rate-limit should not be affected right now, not even on GHE.
Do you need to pay per request?

**Comment by larsxschneider** [comment]
Sure! I administer a GHE appliance with several thousand users and I [monitor](https://github.com/autodesk/hubble) the usage closely to keep it snappy for everyone.  Recently I noticed an unusual high number of API requests from a single user. I investigated the issue and identified `vscode-github` as source of these API requests. 

An additional 55k requests per day won't kill the appliance. However, if your extension becomes popular amongst our engineers, then I could easily deal with  >>100M requests which would certainly cause trouble as the GHE machine and the network interface have physical limits. Of course, I could overcome these limits by throwing more resources at the problem. However, I thought it might be best for everyone if I open a GH to discuss the issue 😉.

**Comment by terrorobe** [comment]
Not Lars, but coming from an GitHub Enterprise Support perspective, one of the prime performance issues we're seeing on GHE appliances from our customers is excessive polling of data to check for changes.

 One of the biggest "offenders" in that regard were CI systems - when you've set your CI system to refresh the status of a branch - say - every 5 minutes and you've got a few hundred repos with 10-100 branches each, this definitely adds up.

For CI systems the obvious solution is to use webhooks, getting notified on change and only sync once a day to see if you missed any webhooks.

---

Looking at Lars' numbers above, if the ~53k requests arrived in an 8 hour time frame this means that we're looking at ~1.86 qps for a single developer.

Assume a mid-sized company has 100 engineers working in VS in parallel, that would balloon to ~186 qps to refresh pull request information among other things. This request rate is negligible for .com and as you mentioned well within the API rate limit. But for GitHub Enterprise customers, the amount of resources available per seat are usually much tighter.

Maybe Lars can share some general statistics of their appliance to get a better understanding of the orders of magnitude involved.

**Comment by KnisterPeter** [comment]
@larsxschneider @terrorobe That makes sense. From extensions perspective the repository in view (identified by the `.git/config`) is very unlikely to change when `vscode` is open.
So I could probably reduce the requests by aggressively caching the repo calls.
The 'pull' calls still need polling since webhooks are probably not feasible on a client without server and firewalls/networks in the middle.

**Comment by KnisterPeter** [comment]
Will be released as 0.27.2

**Comment by larsxschneider** [comment]
> From extensions perspective the repository in view (identified by the .git/config) is very unlikely to change when vscode is open.

That would be true for a single developer working on a repo. It would be different for a team working on a repo, right? Maybe reduce the polling to every 10min or so (that's how SourceTree does it AFAIK).

**Comment by KnisterPeter** [comment]
No, even for bigger teams the repo data should be very stable. It contains the following information:

```ts

export interface GithubRepositoryStruct {
  owner: {
    login: string;
  };
  name: string;
  full_name: string;
  default_branch: string;
  allow_rebase_merge?: boolean;
  allow_squash_merge?: boolean;
  allow_merge_commit?: boolean;
  html_url: string;
  parent?: GithubRepositoryStruct;
}
```

**Comment by KnisterPeter** [comment]
Release is out. Please keep an eye on the request metrics the next days.
Any report back is greatly appreciated.
