### ISSUE TITLE
cannot add personal access token

### ISSUE THREAD

**Issue by stephenmhall** [KnisterPeter/vscode-github#358]
Falling at the first hurdle, when I try to add the token from Github I get an Error "Cannot read property 'connect' of undefined" tried many time with 2 different tokens.

Code-OSS version 1.14.0 with platformio on a Rapsberry Pi 3

**Comment by stephenmhall** [comment]
It's working, not sure how as I still got the error the last time I tried. I had to set the email and name global settings then put in my user name and password to push but its working fine. heyho.
Thanks for getting back to me.

**Comment by KnisterPeter** [comment]
@stephenmhall Glad it did work. I would be really glad if you could describe your setup way step-by-step.
There are a few issues and I would like to smooth them. Its not that easy since everyone who had the setup done will not require it again for a long time.
