### ISSUE TITLE
Automatically push branch when creating new pull-request

### ISSUE THREAD

**Issue by jasonkuhrt** [KnisterPeter/vscode-github#373]
Would solve some of the friction in #114. Here's how [`hub`](https://github.com/github/hub) does it:

```
$ git pull-request --push
```

**Comment by KnisterPeter** [comment]
We have this already. Its called `autoPublish` and need to be enabled:

https://github.com/KnisterPeter/vscode-github/blob/master/package.json#L65-L70

**Comment by jasonkuhrt** [comment]
@KnisterPeter ah cool 👍 Thanks for the prompt tip/reply.
