### ISSUE TITLE
Meaning of origin and upstream unclear

### ISSUE THREAD

**Issue by amueller** [KnisterPeter/vscode-github#379]
This looks awesome.
I'm a bit confused about the usage, though. I have an upstream repository to which I want to monitor the PRs, but never push to, and I have my own fork.
Should ``remote.Name`` be ``"origin"`` or ``"upstream"``?
If I set ``remote.Name`` to ``"upstream"`` I can see the PRs for upstream.

Maybe the use-case of looking at PRs from upstream while only pushing to origin is not supported yet?

Either way, if I do set the remote to ``"upstream"`` I can see the PRs but not check them out.
git log:
```
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :.vscode/settings.json
> git check-ignore -z --stdin
> git show :.vscode/settings.json
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :.vscode/settings.json
> git checkout -q dev-fix-issue-11113
error: pathspec 'dev-fix-issue-11113' did not match any file(s) known to git.
```
This shows origin, not upstream.

**Comment by amueller** [comment]
Thank you for your reply. That doesn't really answer the second part of my question, though (sorry for mixing two questions in an issue).
If I set ``git.remote`` to ``"upstream"`` I still can not check out the PRs and "origin" still apears in the git log.

**Comment by KnisterPeter** [comment]
@amueller Sorry for my late answer. There are two configuration options for this:

```
        "github.remoteName": {
          "type": "string",
          "description": "Defines the name of the git remote. Defaults to 'origin'.",
          "default": "origin",
          "scope": "resource"
        },
        "github.upstream": {
          "type": "string",
          "description": "By default the extension get the repository and user from .git/config. For forks where upstream is a different repository this could be configured here (e.g. microsoft/typescript).",
          "scope": "resource"
        },
```

**Comment by wsmelton** [comment]
I've set the `remoteName` to upstream but it fails to pull the information which I think is because the token instructions don't have enough access.

This is all that VS COde Insiders is showing in the notifications:
```
{"message":"Validation Failed","errors":[{"message":"The listed users cannot be searched either because the users do not exist or you do not have permission to view the users.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
```

**Comment by KnisterPeter** [comment]
@wsmelton Can you please open a separate issue and describe in a bit more detail what you are trying to do? I guess the basic connection to github is already working in your case.
