### ISSUE TITLE
pull-request creation does not respect PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by ajorgensen** [KnisterPeter/vscode-github#382]
Github supports two methods for adding a default pull request template which are documented here (https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/). When creating a pull request from this plugin it appears to simply put in the commit message without adding in the template.

Tangentially it would also be awesome if this plugin could support the ability to edit the commit message before sending up the pull request. For example hub (https://github.com/github/hub) will open `.git/PULLREQ_EDITMSG` before pushing up a pull request which is pre-populated with the PULL_REQUEST_TEMPLATE if it exists. I can open another issue for this if you think its a worthwhile feature.

**Comment by KnisterPeter** [comment]
Thats a nice idea.

**Comment by KnisterPeter** [comment]
Relates to #405
