### ISSUE TITLE
Setup/Update tokens should not require reload

### ISSUE THREAD

**Issue by oddysee** [KnisterPeter/vscode-github#395]
Hi,

I've set up the enterprise token, having passed in the correct GH URL and token. The token has repo & user access levels. I still can't seem to authenticate, resulting in these messages in the output console.

```
Visual Studio Code GitHub Extension
git config --local --get remote.origin.url
git --version
git config --local --get remote.origin.url
GET https://github.dev.mycompany.com/api/v3/user/repos 
401 Bad credentials 
Failed to connect to provider "Connection with GitHub Client failed. Please make sure your git executableis setup correct, and your token has enought access rights."
```

Is there a way I could get some additional debugging output?

Thanks!

**Comment by KnisterPeter** [comment]
Hi @oddysee 
Does this work in your browser `https://github.dev.mycompany.com/api/v3/user/repos` with the given credentials?
Do your company use a corporate proxy to connect to the internet or other services?

**Comment by oddysee** [comment]
Hi @KnisterPeter, a `curl -u username:token https://github.dev.mycompany.com/api/v3/user/repos` works.

Nope, no proxy of any sorts.

An idea that occurred to me was that perhaps the username isn't quite right? My username is `dev-oddysee` which is different to my email address.

**Comment by KnisterPeter** [comment]
@oddysee The username is not relevant, since a token is used. That is independent from username or password.
Can you explain the steps in details you did to setup the extension? A lot of people struggle during setup and I would like to improve it. Details on how you did that would help a lot.

**Comment by oddysee** [comment]
Sure thing…

1. Create a Personal Access Token
<img width="1026" alt="screen shot 2018-06-14 at 8 13 18 pm" src="https://user-images.githubusercontent.com/899902/41406452-ca4a6526-700f-11e8-9f84-62f1f43cde17.png">

2. Setup GitHub Enterprise Token…
<img width="1440" alt="screen shot 2018-06-14 at 8 17 28 pm" src="https://user-images.githubusercontent.com/899902/41406721-916fd758-7010-11e8-852c-37c1ca015f51.png">

3. Enter GitHub Enterprise Hostname
<img width="740" alt="screen shot 2018-06-14 at 8 18 01 pm" src="https://user-images.githubusercontent.com/899902/41406793-c5e05454-7010-11e8-81fb-f4ceb15e80ae.png">

4. Enter Github Enterprise Token
<img width="717" alt="screen shot 2018-06-14 at 8 18 25 pm" src="https://user-images.githubusercontent.com/899902/41406826-de78cc44-7010-11e8-96eb-9291c6f054f2.png">

5. Attempt a plugin command, in this Browse Open Pull Request
<img width="799" alt="screen shot 2018-06-14 at 8 24 43 pm" src="https://user-images.githubusercontent.com/899902/41406898-1c586510-7011-11e8-8d9e-a020b830cbd6.png">

6. Get an auth failure
<img width="1440" alt="screen shot 2018-06-14 at 8 26 54 pm" src="https://user-images.githubusercontent.com/899902/41407000-6bb1ef6e-7011-11e8-8bb2-54999c5f0657.png">

**Comment by KnisterPeter** [comment]
@oddysee After Step 4, can you please execute the command `Reload window` and then Step 5?

**Comment by oddysee** [comment]
Thanks @KnisterPeter, that did it. I feel kinda sheepish about this - have I missed a step in the instructions?

Anyway, this is good to close unless you think there is something to be learned/improved from this?

**Comment by KnisterPeter** [comment]
@oddysee You did not miss anything.
I will keep it open for the reference and help for others and I will update the code so a reload is not required anymore in the future.

**Comment by thetaylormcrae** [comment]
![image](https://user-images.githubusercontent.com/2520379/49693677-57d6b380-fb3f-11e8-8587-a50052eeb11f.png)

Using the same steps listed above, this is what I'm seeing when accessing our GitHub Enterprise instance.

VSCode: 1.29.1
VSCode-GitHub extension: .30.1
