### ISSUE TITLE
Handle git repositories from subfolders

### ISSUE THREAD

**Issue by vladgh** [KnisterPeter/vscode-github#396]
Is it possible to have GitHub support if the actual repo lives in a subfolder of the project? Currently I cannot use the benefits of this extension because I have a workspace layout like:
```
Projects/
  project1/
    .git
    files/
  project2/
    .git
    files/
```
Did I miss a setting that deals with this?

**Comment by KnisterPeter** [comment]
@vladgh I think right now you need to open the folder with the `.git` folder as the root in vscode to have this working.
It would be nice to have it working for your setup as well. I'll add this as enhancement.

**Comment by vladgh** [comment]
Thank you
