### ISSUE TITLE
Please setup your Github Personal Access Token and open a Github project in your workspace

### ISSUE THREAD

**Issue by pzelnip** [KnisterPeter/vscode-github#401]
I've added a GH Personal Access token with repo scopes selected (I even regenerated the token & tried again), and opened up this project: https://github.com/bambora/na-payment-apis-demo

When in the command palette I pick "Github: Browse Open Pull request..." I get the message:

![screen shot 2018-06-21 at 8 48 45 am](https://user-images.githubusercontent.com/414933/41730152-ed1147e4-752f-11e8-97e3-09705f8209b2.png)

I get the same message with a different repo checked out (https://github.com/pzelnip/www.codependentcodr.com) and when trying: "Github: create pull request from current branch in current repository"

VS Code version: 1.24.1
Extension version: 0.29.0
OS: OSX Sierra (10.12.6)

**Comment by icecore2** [comment]
Same here, when in inserting my "GH Personal access token...", it still asking to insert one.
**My setup is:**
**VS Code version:** 1.24.1
**Extension version:** 0.29.0
**OS:** Windows 10 Pro x64

**Comment by KnisterPeter** [comment]
Please try again to insert token and then execute the `Reload window` command.

Duplicates #395

**Comment by pzelnip** [comment]
This did **not** fix the problem.  I re-entered the token & did reload window (as well as trying to quit VS Code & reload it), and Im' still prompted to enter my token.

**Comment by KnisterPeter** [comment]
@pzelnip Is it for a github enterprise, or the public github? Could you please paste the output of the `github` output panel here?

**Comment by pzelnip** [comment]
Public github, the repo I'm working on is https://github.com/bambora/dev.na.bambora.com

Trying again, in the github output panel I'm seeing a bunch of:

```
it config --local --get remote.github.url
Failed to connect to provider "Command failed: git config --local --get remote.github.url\n\n"
git config --local --get remote.github.url
Failed to connect to provider "Command failed: git config --local --get remote.github.url\n\n"
git config --local --get remote.github.url
Failed to connect to provider "Command failed: git config --local --get remote.github.url\n\n"
git config --local --get remote.github.url
Failed to connect to provider "Command failed: git config --local --get remote.github.url\n\n"
git config --local --get remote.github.url
Failed to connect to provider "Command failed: git config --local --get remote.github.url\n\n"
```

**Comment by KnisterPeter** [comment]
@pzelnip Whats in your vscode configuration regarding the github extension?
It should be `git config --local --get remote.origin.url` but instead for you its `remote.github.url`. Looks like a configuration error.

**Comment by pzelnip** [comment]
That was it, I had:

```
"github.remoteName": "github",
```
in my settings.  Removing it fixed the problem, thanks very much!

**Comment by KnisterPeter** [comment]
@pzelnip Your welcome. Glad I could help.
