### ISSUE TITLE
Clarity of entering GitHub key

### ISSUE THREAD

**Issue by Farscaper** [KnisterPeter/vscode-github#412]
I manage to get my key but can't get the part about "GitHub: Set Personal Access Token" to give me a request for it. All I get is 

PS C:\Users\Les> GitHub: Set Personal Access Token
GitHub: : The term 'GitHub:' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ GitHub: Set Personal Access Token
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (GitHub::String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

So, any help appreciated.

**Comment by KnisterPeter** [comment]
@Farscaper You have to open vscode and within a folder with a cloned github project.
Then press `Ctrl+Shift+P` and enter `Github: Set Per...` (Thats a command to execute in vscode).
Then follow the stated process.

**Comment by Farscaper** [comment]
Thanks. That helped.
