### ISSUE TITLE
BitBucket Support

### ISSUE THREAD

**Issue by Mark-Foresta** [KnisterPeter/vscode-github#414]
I see that that you support GitHub as well as GitLab. Have you ever conisdered supporting BitBucket and BitBucket Server.

**Comment by KnisterPeter** [comment]
@Mark-Foresta Would be a nice addition.

**Comment by Mark-Foresta** [comment]
I am not super strong at TypeScript to be honest but I will begin looking into this if you don't mind

**Comment by KnisterPeter** [comment]
Cool. Go on. If any questions arises feel free to ask. :relaxed:

**Comment by lootsy** [comment]
@Mark-Foresta Did you had a look at [CodeBucket](https://marketplace.visualstudio.com/items?itemName=pstreule.codebucket)? Does it satify your needs?
