### ISSUE TITLE
Feature request: provide custom comment when creating a PR

### ISSUE THREAD

**Issue by vincentvanderweele** [KnisterPeter/vscode-github#43]
When you create a PR from the github UI it also lets you add an initial comment, which typically is a more detailed PR description. At least in our workflow, submitting PRs without a description is not ok.

It would be great if we could somehow specify that description straight from VSCode so I wouldn't have to leave the editor at all to create a PR. I have no experience with VSCode extensions, so I'm not completely sure how that should work, though.

Do you think that would be a useful addition? And do you have ideas on how to actually implement this? If you think this is useful and have ideas on how to make it work, I would be happy to help out by submitting a PR, for instance.

**Comment by KnisterPeter** [comment]
Great idea. I would make it optional, so if someone wants comments, then he needs to enable this feature.
The current master branch (not released) does create a comment for the pull request based on the first commit message on that branch. I guess that would be a sane default.

So I would like to see this in the workflow like this:

If the user enables 'custom PR comments', then directly before creating a PR an input dialog opens up (only single-line inputs are available in VSC).
This input in then used as body for the PR.

Fine?

**Comment by vincentvanderweele** [comment]
Sounds good! I'll have a look sometime soon 👍
