### ISSUE TITLE
VS Code plugin saying password authentication is not available.

### ISSUE THREAD

**Issue by b3rgman** [KnisterPeter/vscode-github#441]
I was using the github plugin successfully. not I receive the error password authentication is not available.  Here are my steps

These are all in VC Code. I installed the github module
image

I added the personla access token

image

I cloned my repo
image

I made a change and did git commit

image

I pushed the code and get this message

image

image

My token is there. as I can remove it

image

I hope this makes it a little more clear. I followed the same steps on my laptop and it is still working.

**Comment by KnisterPeter** [comment]
@b3rgman First of all thanks for reporting your issue.
But unfortunately I don't get what your problem is about. Can you please give a bit more info?

**Comment by KnisterPeter** [comment]
@b3rgman Looks like you are having problem operating with git. This extension does not `push` anything. I think your problem is related to the vscode git code, not the github code.
Please open a separate issue in the vscode repository.
