### ISSUE TITLE
High CPU usage in diffs

### ISSUE THREAD

**Issue by borekb** [KnisterPeter/vscode-github#443]
Hi, I'm cross-posting an issue from https://github.com/Microsoft/vscode/issues/57697#issuecomment-427832382 which hints at high CPU usage cause by this extension in case of diffing larger files. Props to @alexandrudima for finding it.

**Comment by KnisterPeter** [comment]
Thanks, I'll have a look at this.

**Comment by KCraig-StepStone** [comment]
Have to disable this plugin today as it causes my system to lock up with high CPU usage when opening files with more than 4000 lines. Possibly smaller files but that is where I really noticed it since it would prevent me from even moving my mouse around. Through testing I found it is only this plugin that causes this issue.

**Comment by danguilherme** [comment]
I got the same error in VS Code as pointed in #481.
It happened when diffing a `yarn.lock` file (13k+ lines).

Here's the CPU profile provided by Code, if it helps: [KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/2884803/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)

**Comment by KnisterPeter** [comment]
@danguilherme Thanks for reporting. Good catch that it happens with large files. It may be related to the `LinkProvider` and `HoverProvider`.

I'll look into this when I find some time.

**Comment by AnalogMemory** [comment]
I've been encountering this issues as well the past couple days

**Comment by KnisterPeter** [comment]
I disabled issue scanning for now. This should reduce cpu load.

**Comment by qreeves** [comment]
[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/4341658/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)
