### ISSUE TITLE
Bug: When changing branches, statusbar icon does not change

### ISSUE THREAD

**Issue by tomerMP** [KnisterPeter/vscode-github#444]
When working switching between 2 branches each with PR, the statusbar icon remains on the PR of the previous branch.
When checking out master the statusbar icon remains on the PR of the previous branch and does not change back to "create PR" icon as expected

- Original branch with PR

![image](https://user-images.githubusercontent.com/30149311/46664979-2129fe80-cbcb-11e8-8f21-395d99e5b23e.png)

- After checking out master branch

![image](https://user-images.githubusercontent.com/30149311/46665062-5b939b80-cbcb-11e8-907e-9a2487ea26bb.png)

- Expected master branch:

![image](https://user-images.githubusercontent.com/30149311/46665218-e6749600-cbcb-11e8-8b30-71e90378a92f.png)

- Checking out other branch also with PR (old PR remains):

![image](https://user-images.githubusercontent.com/30149311/46665084-76fea680-cbcb-11e8-8d82-ed77a1aa0cae.png)

- When going from master to branch with PR:

![image](https://user-images.githubusercontent.com/30149311/46665335-30f61280-cbcc-11e8-8bd6-d736dec4ee79.png)

To fix issue requires application restart while in required branch.
- After app restart:

![image](https://user-images.githubusercontent.com/30149311/46665159-bfb65f80-cbcb-11e8-9ccd-eb2c89d4d484.png)

**Comment by KnisterPeter** [comment]
@tomerMP Is this persistent, or does it change after a few seconds or a minute? There is no hook in vscode to be notified about branch changes so I'll track that by pulling the current branch every now and then.

**Comment by tomerMP** [comment]
Not only is it persistent, there is another state that I did not see earlier where after opening VSCode app while checked out on PR branch the icon just never appears:

![image](https://user-images.githubusercontent.com/30149311/46669717-ef1f9900-cbd8-11e8-887b-97ce2db285cb.png)

**Comment by KnisterPeter** [comment]
Okay, I have to inspect this. Thanks for reporting.
