### ISSUE TITLE
GitHub Enterprise error - Connection with GitHub Client failed

### ISSUE THREAD

**Issue by thetaylormcrae** [KnisterPeter/vscode-github#467]
Using the same steps listed in issue #395, this is what I'm seeing when accessing our GitHub Enterprise instance.

![image](https://user-images.githubusercontent.com/2520379/49693691-b865f080-fb3f-11e8-8d7d-04e405de9495.png)

VSCode: 1.29.1
VSCode-GitHub extension: .30.1

_Originally posted by @thetaylormcrae in https://github.com/KnisterPeter/vscode-github/issue_comments#issuecomment-445512014_

**Comment by KnisterPeter** [comment]
@thetaylormcrae What OS are you on? Where in your path is your git binary installed?

**Comment by thetaylormcrae** [comment]
@KnisterPeter : My OS is Windows 10 Pro build 1803 and Git binary is installed at C:\Program Files\Git.

**Comment by KnisterPeter** [comment]
@thetaylormcrae If you open a cmd terminal in windows and type 'git' does it work and find the command or does it fail? Right now the extension expects your git executable in your path. Otherwise you can try to configure `github.gitCommand` in vscode settings as path to your git executable.

**Comment by KnisterPeter** [comment]
@thetaylormcrae And after configuration you may need to run 'Reload window'.

**Comment by thetaylormcrae** [comment]
I'm able to type 'git' into PowerShell / CMD and get back the 'These are common Git comands...' message. I'll try specifying the Git path using that option in VSCode and see if it makes a difference.

**Comment by KnisterPeter** [comment]
@thetaylormcrae It would be great if you can report back here. At least as reference for others if it did work.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : Unfortunately, I got the same error after specifying the full path to the git.exe file. Listed below is my user settings (json) file.

{
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },

    "gitlens.remotes": [
        {
            "domain": "github.ascension.org",
            "type": "GitHub"
        }
    ],

    "github.gitCommand" : "C:/Program Files/Git/cmd/git.exe"
    }

    "markdown.extension.toc.orderedList": true,
    "git.confirmSync": false,
    "workbench.colorTheme": "Ayu Mirage",
    "git.defaultCloneDirectory": "C:/Scripts/Repository-WorkInProgress",
    "git.enableSmartCommit": true,
    "pandoc.htmlOptString": "-s -t html5 -c css/style.css",
    "window.zoomLevel": 0,
    "git.autofetch": true,
    "cSpell.language": "en"
}

**Comment by KnisterPeter** [comment]
@thetaylormcrae Can you then please verify that your GHE is available at `<protocol>//<hostname>/api/v3`? Besides than this I have no clue what can go wrong. The error messages usally means that either your git binary is not found or the endpoint cannot be reached over network.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : Sounds good. Here's a fresh copy of the output
![untitled](https://user-images.githubusercontent.com/2520379/49742611-7f706d80-fc5e-11e8-8bf1-97b3ca07e72b.png)

**Comment by KnisterPeter** [comment]
@thetaylormcrae Its clearly the request which fails. So either your token is not found (for whatever reason) or it has not enough access rights, or I don't know...

**Comment by thetaylormcrae** [comment]
@KnisterPeter : Good to know. Is there any further debugging that can be enabled to see how the extension pulls in the token that's stored in VSCode?

**Comment by KnisterPeter** [comment]
@thetaylormcrae No, to get deeper into it you need to compile your own version of the extension.
Its not that hard tho. Clone the repo, open it in code, and start a debugging session.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : Sounds good! If I find anything that stands out for this issue, I'll make sure to report back here.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : Not sure what I'm doing wrong, but when I start a debug session after cloning the repository, this is what I get in the [Extension Development Host] instance:

Activating extension 'KnisterPeter.vscode-github' failed: Cannot find module 'C:\Scripts\vscode-github-1\out\src\main'.

**Comment by KnisterPeter** [comment]
Did you install all dependencies with yarn and started a build? The default build in vscode should work.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : My apologies. I didn't properly install the dependencies. After that was completed, the error is no longer present. After setting up the secure token and attempting to check pull requests on a GHE repository, I got the following error.

Extension 'KnisterPeter.vscode-github' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
Extension 'KnisterPeter.vscode-github' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
GET https://github.ascension.org/api/v3/user/repos 
Failed to connect to provider "Connection with GitHub Client failed. Please make sure your git executableis setup correct, and your token has enought access rights."
GET https://github.ascension.org/api/v3/user/repos 
GET https://github.ascension.org/api/v3/user/repos 
Failed to connect to provider "Connection with GitHub Client failed. Please make sure your git executableis setup correct, and your token has enought access rights."
GET https://github.ascension.org/api/v3/user/repos 
Error: Connection with GitHub Client failed. Please make sure your git executableis setup correct, and your token has enought access rights.
	at WorkflowManager.<anonymous> (C:\Scripts\vscode-github-1\out\src\workflow-manager.js:39:23)
	at Generator.throw (<anonymous>)
	at rejected (C:\Scripts\vscode-github-1\out\src\workflow-manager.js:14:65)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by KnisterPeter** [comment]
@thetaylormcrae Hmm, then the only option would be to set a breakpoint at apropriate positions or I create a branch with a few more log output for you to debug this further. Whatever is easier for you.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : I like the option of a separate branch to isolate the troubleshooting.

**Comment by thetaylormcrae** [comment]
@KnisterPeter : What would I need to do to enable further logging on this extension? Digging through the code now, but not sure where to start.

**Comment by KnisterPeter** [comment]
@thetaylormcrae Sorry for not responding. I've had a busy time lately.
A good starting point would be this line https://github.com/KnisterPeter/vscode-github/blob/master/src/workflow-manager.ts#L81
Its the error you have in the logs regarding the provider connection.

By the way did you tried the github extension from microsoft? Its quite good and does a lot of this extension but better and they have a bigger team on it.

**Comment by thetaylormcrae** [comment]
Thank you, @KnisterPeter ! I'll dig into that and see what I can find. In terms of the GitHub extension from Microsoft, I run into a similar issue where the extension doesn't seem to load. Interestingly enough, even though my remotes are HTTPS, it's asking about .ssh config.

```VSCode
[Info] C:\Users\TMCRA002\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\TMCRA002\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch develop
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch develop
```

I'll let you know what I find on your extensions this week. :-).
