### ISSUE TITLE
ERR Command failed: git config --local --get-regexp ^remote.*.url

### ISSUE THREAD

**Issue by drawcard** [KnisterPeter/vscode-github#469]
For some reason my "Prettier" extension stopped formatting pages suddenly in VS Code latest stable. On looking at the debug console this error occurs on save, tied to vscode-github:
![image](https://user-images.githubusercontent.com/1435638/49840041-b29f3200-fe01-11e8-8b9f-09726e85ea8c.png)

**Comment by drawcard** [comment]
Update: sorry the Prettier issue turned out to be something else. Ignore that part :)

**Comment by drawcard** [comment]
Possibly related to: https://github.com/prettier/prettier/issues/5582 as it happens to a whole other bunch of tags in my doc.

**Comment by KnisterPeter** [comment]
@drawcard Thanks for reporting. This has nothing to do with prettier. This extension probably isn't able to detect your git remotes. It should give up after the first try and notify the users.
I'll flag this as issue.
