### ISSUE TITLE
Authentication on Linux fails

### ISSUE THREAD

**Issue by mattouille** [KnisterPeter/vscode-github#477]
The authentication dialog just reloads vscode over and over. It does not actually do anything. I'm on Kubuntu 18.04. If there's a way around this it'd be much appreciated.

![screenshot_20190117_111917](https://user-images.githubusercontent.com/8207468/51336492-463fd000-1a4a-11e9-85f7-345bbadd83f4.png)

**Comment by KnisterPeter** [comment]
@mattouille I'm sure you want to report this here https://github.com/Microsoft/vscode-pull-request-github
