### ISSUE TITLE
"Browse current file" / "Browse project" fail when repo in detached head state

### ISSUE THREAD

**Issue by nrser** [KnisterPeter/vscode-github#499]
Extension tries to run

    $ git symbolic-ref -q HEAD

to get the branch, but this fails when in a detached head state (have a project checked out at a release tag, which is something I commonly do for local source reference).

**Comment by KnisterPeter** [comment]
@nrser Thanks for reporting

**Comment by nrser** [comment]
I think you can't really pick out which tag you're "on" if multiple tags point to the same commit, but in that case it would be nice to send you to browse the source at the HEAD commit.
