### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by ajsb85** [KnisterPeter/vscode-github#51]
Hi @KnisterPeter

Can you create .gif files to know how use your extension?

Thank you!

**Comment by KnisterPeter** [comment]
Contributions are welcome

**Comment by KnisterPeter** [comment]
I've added at least some textual usage instructions for now
https://github.com/KnisterPeter/vscode-github#usage

**Comment by mcascone** [comment]
I've installed this extension, and when I try to execute `github:>github: Setup GitHUb Enterprise Token` I get this error:
```Error command 'vscode-github.setGitHubEnterpriseToken' not found```

**Comment by KnisterPeter** [comment]
@mcascone Can you please open a new issue and attach the output of the console as well?

**Comment by mcascone** [comment]
Thanks for the reply. I created issue #126.
