### ISSUE TITLE
preset commit message not working

### ISSUE THREAD

**Issue by mcascone** [KnisterPeter/vscode-github#534]
Issue Type: <b>Bug</b>

I have a git commit message template in my repo, that works on the CLI, but is not in the commit message field by default in Code. How do I make this happen, or is it a missing feature? Thanks!

Extension version: 0.30.2
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (1.27GB free)|
|Process Argv|../../.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by KnisterPeter** [comment]
@mcascone This does not work with this extension right now
