### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by eforneas** [KnisterPeter/vscode-github#536]
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.2`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/Macbook/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment]
Duplicate #443
