### ISSUE TITLE
Stuck in Command

### ISSUE THREAD

**Issue by evanricard** [KnisterPeter/vscode-github#554]
<details>
<summary>Info Pics</summary>

![image](https://user-images.githubusercontent.com/30779615/61068763-c41cdc80-a3d8-11e9-8687-91cb14a0eea1.png)

![image](https://user-images.githubusercontent.com/30779615/61068783-d26af880-a3d8-11e9-8d4f-870e5117dc06.png) ^ 

</details>

Hi Peter, I've downloaded your extension and configured a base path to point to to look for git projects; however, it seems like it is unable to find any .git information and will not show any projects. Any help would be appreciated, thanks.

**Comment by KnisterPeter** [comment]
@evanricard It seem that you are configuring the `gitProjectManager` extension not this one. Have look at their repository: https://github.com/felipecaputo/git-project-manager
