### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mohnuris** [KnisterPeter/vscode-github#558]
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Cyber Army\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment]
Duplicate #443
