### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ericanandagds** [KnisterPeter/vscode-github#565]
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.2`
- OS Version: `Windows_NT ia32 6.3.9600`
- VSCode version: `1.37.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Familia\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment]
Duplicate of #443
