### ISSUE TITLE
Feature request: Github - Browse current file (with multi-line selection)

### ISSUE THREAD

**Issue by ivanmilov** [KnisterPeter/vscode-github#578]
Can you please extend current behaviour to generate multi line selection link like this:

https://github.com/KnisterPeter/vscode-github/blob/430919086679e525587c21d1ed23dc9b50f60592/src/commands/browse.ts#L71:L72

**Comment by ivanmilov** [comment]
can be done like there:
https://github.com/KnisterPeter/vscode-github/pull/580

**Comment by KnisterPeter** [comment]
Released with v0.30.3

**Comment by ivanmilov** [comment]
resolved
