### ISSUE TITLE
Support of PRs from forks

### ISSUE THREAD

**Issue by artem-sidorenko** [KnisterPeter/vscode-github#58]
Thanks for a cool extension!

I tried to create a PR the fork setup and the PR got created in the fork and not in the base project. It would be nice to have it fixed :)

**Comment by KnisterPeter** [comment]
Definitely a requirement. :smile:

**Comment by KnisterPeter** [comment]
Released as 0.10.0

**Comment by artem-sidorenko** [comment]
@KnisterPeter many thanks!:)

**Comment by KnisterPeter** [comment]
Your welcome :smile:
