### ISSUE TITLE
Add support for ~/.ssh/config usage in remote URLs

### ISSUE THREAD

**Issue by gschaffner** [KnisterPeter/vscode-github#604]
If a user has a repo configured with remote

```terminal
$ git config --local --get remote.origin.url
gh:myuser/myrepo
```

and a configuration `~/.ssh/config` ([docs](https://linux.die.net/man/5/ssh_config))

```
Host gh
    HostName github.com
    User git
```

then this configuration will map `gh:myuser/myrepo` to the appropriate `git@github.com:myuser/myrepo` when used with `git` from the terminal.

However, if one tries to use a repo with this remote URL with this extension, commands fail with `Error: Not a Provider remote!`.

Is there any possibility of adding support for parsing `~/.ssh/config` files?

**Comment by KnisterPeter** [comment]
Nice idea. I'm open for PRs.
