### ISSUE TITLE
git log command fails when branch is local only

### ISSUE THREAD

**Issue by cbenz** [KnisterPeter/vscode-github#61]
When creating a pull request with the "Create pull request in the current branch in current repository (quick)" command, or with the "Create pull request" command, I get this error:

```
Command failed: git log --reverse --right-only --format=%h origin/master..origin/rename-functions
```

The operation is aborted. No error message in the developer tools of vscode.

> Note: I have set my token properly and the "Browse open pull requests" command works fine.

**Comment by cbenz** [comment]
From the command line this error is displayed:

```sh
git log --reverse --right-only --format=%h origin/master..origin/rename-functions
fatal: ambiguous argument 'origin/master..origin/rename-functions': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I understand that my `rename-functions` branch is local only and has never been pushed.

The error message should be clearer, or the extension could ask if I'd like to push first.

**Comment by KnisterPeter** [comment]
Thank for the report. I think there should be a notification to push the branch first.

**Comment by guillaumemolter** [comment]
There is a similar behavior if you try to open a PR on an unpublished branch. I will open a separate issue next time I encounter the use case (so I can properly document with snippets and screenshots).
