### ISSUE TITLE
github access token can't work

### ISSUE THREAD

**Issue by bmxbmx3** [KnisterPeter/vscode-github#626]
I have followed the instruction to set "GitHub: Set Personal Access Token" in vscode,but then every time I opened vscode,the github login dialog always poped up and reminded me that I should enter user name and password again .... it seemed that the personal access token I have set in your extension didn't work,how should I solve this problem?

**Comment by KnisterPeter** [comment]
@bmxbmx3  I think you may have different github extensions installed.
This one never asks for username and password.
