### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kunvar13** [KnisterPeter/vscode-github#628]
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.43.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\KalpeshK\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment]
Duplicate #443
