### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by the5ereneRebe1** [KnisterPeter/vscode-github#629]
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\HIMANSHU\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mavaddat** [comment]
* Issue Type: `Performance`
 * Extension Name: `vscode-github`
 * Extension Version: `0.30.3` (2019-10-27)
 * OS Version: `Windows_NT x64 10.0.19592`
 * VSCode version: `1.44.0-insider` (system setup)
 
 ⚠️ Make sure to **attach** this file from your _home_-directory:

[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/4397615/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)

**Comment by mavaddat** [comment]
It looks like you forgot to attach the file that it specifies from your home directory.

> ⚠️ Make sure to **attach** this file from your _home_-directory:
> ⚠️`C:\Users\HIMANSHU\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

**Comment by the5ereneRebe1** [comment]
[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/4399775/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)

**Comment by KnisterPeter** [comment]
Duplicate #443
