### ISSUE TITLE
Failed to connect to provider "No token found for host github.com"

### ISSUE THREAD

**Issue by KlepiT-cmd** [KnisterPeter/vscode-github#631]
Hi,

I'm trying to connect my vscode and my github account but I have a problem.
If I start the vscode and check the source control tab I see nothing.
The output:

**git config --local --get remote.origin.url
Failed to connect to provider "No token found for host github.com"**

Could you help me please to fix it?
git version: 2.26.0.windows.1
vscode version: 1.43.2

Many thanks

**Comment by KnisterPeter** [comment]
Hi @KlepiT-cmd,
as described [here](https://github.com/KnisterPeter/vscode-github#setup-personal-access-token) you need to create a personal access token.
