### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by linkeshkanna** [KnisterPeter/vscode-github#647]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 9605,
		"activateCallTime": 23,
		"activateResolvedTime": 30,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "KnisterPeter.vscode-github",
				"_lower": "knisterpeter.vscode-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by KnisterPeter** [comment]
Hi @linkeshkanna,
whats the issue here? I don't understand your request.

**Comment by linkeshkanna** [comment]
codeloadingtime took too much and VS Code automatically popped up to report this issue with the above content.

**Comment by KnisterPeter** [comment]
Oh I see.
I currently don't use it that much, therefore I'll flag this as `help wanted` if someone wants to chim in.
