### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rajkamalg356** [KnisterPeter/vscode-github#672]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.47.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by KnisterPeter** [comment]
Sorry, but with this error message its not possible to fix anything.
