### ISSUE TITLE
Auth setup with token for enterprise

### ISSUE THREAD

**Issue by Craig323** [KnisterPeter/vscode-github#681]
Trying to work with github enterprise
Read the readme, have a token, ctrl+shift+p, GitHub: Set Personal Access Token, paste the token
Source Control, clone repo, then this error
What else is needed to setup the auth?

> git clone https://github.company.com/somePath/someRepo.git c:\Users\name\VSC\someRepo --progress
Cloning into 'c:\Users\name\VSC\someRepo'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.company.com/somePath/someRepo.git/'

**Comment by KnisterPeter** [comment]
@Craig323 I think you may need to reload/restart vscode
