### ISSUE TITLE
Feature request: PR link clickable

### ISSUE THREAD

**Issue by guillaumemolter** [KnisterPeter/vscode-github#69]
When you create a PR. It would be great if the PR name (ie: #271) in the notification bar was an active link to the GitHub PR.

![screen shot 2017-03-16 at 14 03 22](https://cloud.githubusercontent.com/assets/1478527/24011537/78378950-0a51-11e7-90f8-74724794fed6.png)

While it's very convenient to be able to create the PR from Code, I usually like to review and rename it as well as apply some labels and milestones.

Same thing for the status bar:
![screen shot 2017-03-16 at 14 07 12](https://cloud.githubusercontent.com/assets/1478527/24011719/ea917cc2-0a51-11e7-9a2b-d7012f0429bf.png)

**Comment by KnisterPeter** [comment]
I'm not sure if it is possible to have a link in the notifications. I'll try that its a good idea.
Labels and milestones should go to a separate feature request.

**Comment by guillaumemolter** [comment]
@KnisterPeter hmmm I didn't meant I want to be able to manage labels ans milestones (Re #72 #73 ), I was explaining why having a link to Github.com would be useful (to click on it and manage labels, milestones).

**Comment by KnisterPeter** [comment]
Ah, I see. But managing labels and milestones could be useful. :smile:

**Comment by KnisterPeter** [comment]
Will be released with 0.11.0
By the way, the status bar entry already has a function assigned to it which is creating or merging the pull request. So it is currently not good to change that.

**Comment by guillaumemolter** [comment]
Thanks! The "status" bar was more of a "nice to have" so it's fine if not possible. I think between #76 and #75 we now have multiple options to achieve this which is great.
