### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rajthun** [KnisterPeter/vscode-github#695]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rajthun** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1309,
		"activateCallTime": 35,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.js-debug",
				"_lower": "ms-vscode.js-debug"
			},
			"activationEvent": "onDebugResolve:node"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Can't find Node.js binary \"node\": path does not exist. Make sure Node.js is installed and in your PATH, or set the \"runtimeExecutable\" in your launch.json"
		},
		{
			"name": "Error",
			"message": "Can't find Node.js binary \"node\": path does not exist. Make sure Node.js is installed and in your PATH, or set the \"runtimeExecutable\" in your launch.json"
		}
	]
}
```

**Comment by KnisterPeter** [comment]
@rajthun  This is not very helpful on its own. Please provide a complete description what happened how to reproduce.

**Comment by rajthun** [comment]
SFDX commands like Authorize org, retrieve & deploy are unresponsive and its keep on running for hours . Also Salesforce extension pack is unresponsive and shows text as performance issues. Refer screenshot and Please do the needful.

![image](https://user-images.githubusercontent.com/71089507/94948240-a3203a00-04fc-11eb-8c78-4228eff1fced.png)


Extension version: 49.11.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18362

System Info
Item	Value
CPUs	Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)
GPU Status	2d_canvas: unavailable_software
flash_3d: disabled_software
flash_stage3d: disabled_software
flash_stage3d_baseline: disabled_software
gpu_compositing: disabled_software
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
opengl: disabled_off
protected_video_decode: disabled_off
rasterization: disabled_software
skia_renderer: disabled_off_ok
video_decode: disabled_software
vulkan: disabled_off
webgl: unavailable_software
webgl2: unavailable_software
Load (avg)	undefined
Memory (System)	7.88GB (2.65GB free)
Process Argv	--crash-reporter-id d39c7481-d5bb-4584-a1e8-dc84328e7ec8
Screen Reader	no
VM	0%

**Comment by KnisterPeter** [comment]
@rajthun I think you might be in the wrong repository.
I don't understand your request and this extension has nothing to do with salesforce and SFDX
