### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vishnukannas** [KnisterPeter/vscode-github#696]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.49.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by KnisterPeter** [comment]
Not able to do anything with this report.
Please provide a detailed explanation how to reproduce.
