### ISSUE TITLE
Feature Request: Open GitHub Repo

### ISSUE THREAD

**Issue by guillaumemolter** [KnisterPeter/vscode-github#70]
I would love a new command that simply open the GitHub repo homepage:

![screen-shot-2017-03-16-at-14 11 05](https://cloud.githubusercontent.com/assets/1478527/24011985/c4ba90b4-0a52-11e7-91ec-a8fabc3b11ba.jpg)

As a convenient quick shortcut to access issues/milestones/wiki etc.

**Comment by KnisterPeter** [comment]
Will be released with 0.11.0

**Comment by guillaumemolter** [comment]
Thanks!
