### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by IrfanGhuori** [KnisterPeter/vscode-github#705]
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.4`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\mirfa\AppData\Local\Temp\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment]
Duplicate of #443
