### ISSUE TITLE
Feature request: Add command to manage reviewer, assignees in pull request

### ISSUE THREAD

**Issue by asimolmez** [KnisterPeter/vscode-github#71]
Can we have an ability that adds reviewer or assignees in `Create pull request` command? If your answer is no, yo can add this as a feature request.

**Comment by KnisterPeter** [comment]
I would prefer to have a separate command for that. I would overload the UI too much to have everything in one command. But its a nice idea.

**Comment by KnisterPeter** [comment]
This will be released with 0.12.0
