### ISSUE TITLE
Authentication Keeps Getting Rejected

### ISSUE THREAD

**Issue by PhantomNimbi** [KnisterPeter/vscode-github#713]
Issue Type: <b>Bug</b>

- Attempt to sing into github
- Copy the code it gives
- Click Signing into github in the VSCode status bar
- Paste the code into the box
- Type your username into the username box
- Type your password into the password box

Extension version: 0.30.4
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.8.18-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor (6 x 1755)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|11.70GB (3.54GB free)|
|Process Argv|--extensions-dir=/home/nimbi/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --no-sandbox --crash-reporter-id 39531b6e-e1ec-4b28-a538-65c90d9afdb1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by KnisterPeter** [comment]
Hi @PhantomNimbi, I think you refer to this extension, don't you?
https://github.com/microsoft/vscode-pull-request-github

**Comment by PhantomNimbi** [comment]
yep, that's the one.

**Comment by KnisterPeter** [comment]
Then I'll close this one :wink: 
You should address your problem there.
