### ISSUE TITLE
Failure to integrate with GitHub

### ISSUE THREAD

**Issue by designtechti** [KnisterPeter/vscode-github#744]
Issue Type: <b>Bug</b>

    When I try to link my GitHub Account to VS Code - Insiders,  I follow all steps that appears in the browser, and the message "Success" appears. However, in VS Code it is only displayed in the status bar "Signing in to github.com..." but it does not connect at all! 
    Seeing that this occurs, I try to paste the token into the IDE and, even so, it doesn't work. I hope you can solve it! 
    I'm using the Linux Parrot Security OS 4.10 distribuition. Thanks in advance!

Extension version: 0.30.4
VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T09:00:24.919Z)
OS version: Linux x64 5.7.0-2parrot2-amd64 snap

**Comment by KnisterPeter** [comment]
The message `Signing in to github.com...` is created by [this extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github).
I think the issue belongs there.

**Comment by designtechti** [comment]
Even if I did not run the "GitHub Pull Request" command in Command Pallet and much less have this extension installed? I don't think so! 

This error happens whenever I click on "Clone Repository" or do any function in VS Code that needs to be linked with GitHub

**Comment by KnisterPeter** [comment]
There is no "Clone Repository" in this extension.

**Comment by designtechti** [comment]
It is not the extension I am referring to, it is the VS Code itself that has the option to Clone a repository in the Source Control tab.

**Comment by KnisterPeter** [comment]
I don't get it. Why do you open an issue in this extensions repo if the problem you have is with vscode during cloning?

**Comment by designtechti** [comment]
Dude, it's not just time to clone repositories ... it's in any function I do in VS code that I need GitHub, it happens!  

And when it happens, it always opens a window saying that you have to enable the GitHub extension.  Get it now?

**Comment by KnisterPeter** [comment]
No, I still don't get it. What window? Please add a screenshot here. Also what do you mean with the initial error message 'Signing in to github.com...'. It's not from this extension.

**Comment by designtechti** [comment]
I'll send this ASAP! I'm on my smartphone now

**Comment by designtechti** [comment]
This extension is enable globally
![Captura de ecrã no 2021-02-02 14-31-21](https://user-images.githubusercontent.com/59212312/106639231-a8f65c80-657c-11eb-8ba6-e71442bc21cb.png)

**Comment by KnisterPeter** [comment]
These dialogs and questions are not from this extension. You can safely uninstall it and will still have the same result.
I do not even do oauth with the browser, but request to create a token manually.

**Comment by KnisterPeter** [comment]
As I can see in your last screenshot, you also have the github extension from microsoft installed. That one is causing your trouble. It's the one I linked to in my first answer. Please report your problem there.

**Comment by designtechti** [comment]
The extension that you're talking about isn't installed! Look it again! 

![Captura de ecrã no 2021-02-02 17-27-20](https://user-images.githubusercontent.com/59212312/106658647-760c9280-6595-11eb-8c55-5983b7ad4d06.png)

**Comment by KnisterPeter** [comment]
Okay again, this kind of authentication isn't from this extension. It does open such a window.
In the readme you can see how to authenticate.

Others than that, feel free to send a Pull Request that will fix your problem. I cannot do that, because the source of your problem is not in this repository.
