### ISSUE TITLE
"Checkout Open Pull Request" asks for "Select a ref to checkout"

### ISSUE THREAD

**Issue by mcMickJuice** [KnisterPeter/vscode-github#763]
When I select a PR to checkout via the "Checkout Open Pull Request" action, I am then asked to "Select a ref to checkout".  This is new behavior. Previously upon selecting a PR, it would automatically checkout the branch corresponding to that PR.

The remote my repo points to is a Github Enterprise repo, if that's important.

Repro Steps:
- select "Checkout Open Pull Request"
- select PR that I want to checkout
- I'm then prompted to "Select a ref to checkout"

Desired outcome:
Upon selecting a PR, the branch corresponding to that PR is checked out without prompting me to select a ref

**Comment by KnisterPeter** [comment]
Hi @mcMickJuice, the last release of this extension is from sep 2020. Can you specify 'new behavior'?

**Comment by mcMickJuice** [comment]
The new behavior is the "Select a ref to checkout". This started about a month ago. I'm not seeing any logs pertaining to this prompt so perhaps it's a change in githubs api?

**Comment by KnisterPeter** [comment]
Not sure what the reason is. I would accept a PR if you want to dig into this change to fix it.
