### ISSUE TITLE
Unable to Sign In Into Github

### ISSUE THREAD

**Issue by Theory-of-Everything** [KnisterPeter/vscode-github#797]
Issue Type: <b>Bug</b>

Vscode - oss version: 1.55.2
OS: Void Linux x86_64

Steps to Reproduce:
1. Make sure Extensions 'Github' and 'Github Pull Requests and Issues' are installed 
2. Attempt to Sign into Github using the person icon in the bottom left hand corner, clicking 'Sign in to use Github Pull Requests and Issues' prompt.
3. Click continue on the open web page
4. Copy the Sign in token fomr the web page
5. Click the 'Signing into github.com...' prompt in the status bar on the bottom.
6. Paste in the token.

Expected Result:
Login to Github Successfully

Actual Result:
and Error is thrown: (Error: Writing login information to the keychain failed with error 'Unknown or unsupported transport “disabled” for address “disabled:”'.)

Extension version: 0.30.6
VS Code version: Code - OSS 1.55.2 (Commit unknown, 2021-04-26T07:16:37.496Z)
OS version: Linux x64 5.11.16_1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2186)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|3.74GB (0.28GB free)|
|Process Argv|--app=/usr/lib/code-oss/bin/../resources/app --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|bspwm|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|bspwm|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by KnisterPeter** [comment]
@Theory-of-Everything This extension has nothing to do with 'Github Pull Requests and Issues'. That one is created by microsoft and issues should be filed over there: https://github.com/microsoft/vscode-pull-request-github

This extension also isn't using 'Sign into Github using the person icon' but instead, according to our README (https://github.com/KnisterPeter/vscode-github#setup-personal-access-token), a PAT.
