### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sikandar787** [KnisterPeter/vscode-github#824]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.6`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by sikandar787** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 14069,
		"activateCallTime": 6,
		"activateResolvedTime": 2,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "KnisterPeter.vscode-github",
				"_lower": "knisterpeter.vscode-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by KnisterPeter** [comment]
There is notion about what is going wrong here. Please add your error to have this reopened.
