### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Coder-Manthan** [KnisterPeter/vscode-github#847]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.6`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11994,
		"activateCallTime": 11,
		"activateResolvedTime": 47,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "KnisterPeter.vscode-github",
				"_lower": "knisterpeter.vscode-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

Github extension is being unresponsive and preventing other extensions from doing their work.

**Comment by KnisterPeter** [comment]
@Coder-Manthan Thanks for reporting. A pull request to fix this is very welcome.
