### ISSUE TITLE
invalid remotename bug

### ISSUE THREAD

**Issue by adlternative** [KnisterPeter/vscode-github#856]
Hi, I tried to create a git remote named "github",

```sh
git remote add github git@github.com:adlternative/lib_liburing.git 
```

and then after I reopening vscode, I saw this in vscode-github log output:

```sh
Failed to connect to provider "Command failed with exit code 1: git config --local --get remote.origin.url"
git branch
git symbolic-ref -q HEAD
git for-each-ref --format='%(upstream)' 'refs/heads/main'
git config --local --get remote.origin.url
git config --local --get-regexp ^remote.*.url
Command failed with exit code 1: git config --local --get remote.origin.url
Error: Command failed with exit code 1: git config --local --get remote.origin.url
    at makeError (/home/adl/.vscode/extensions/knisterpeter.vscode-github-0.30.6/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/adl/.vscode/extensions/knisterpeter.vscode-github-0.30.6/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


Your configuration contains an invalid remoteName. Consider setting the `github.remoteName` setting with one of these:

github

```

Thanks.

**Comment by KnisterPeter** [comment]
The extension tries to automatically determine the remote name.
If that fails you can set it in the configuration:

https://github.com/KnisterPeter/vscode-github/blob/c93d4a2301dffb4f71b48575ec1141ceea7a9a3e/package.json#L43-L47

**Comment by adlternative** [comment]
> The extension tries to automatically determine the remote name.
> If that fails you can set it in the configuration:
> 
> https://github.com/KnisterPeter/vscode-github/blob/c93d4a2301dffb4f71b48575ec1141ceea7a9a3e/package.json#L43-L47

Thanks! But I really think this is a design error.

**Comment by KnisterPeter** [comment]
@adlternative a pull request which updates this behavior for the good is very welcome.

**Comment by tkazik** [comment]
I also just stumbled across this issue (see also [here](https://stackoverflow.com/questions/51524443/heroku-configuration-contains-an-invalid-remotename)).
My guess is that somehow the regex (`git config --local --get-regexp ^remote.*.url`) is not parsed correctly and the extension is then expecting the remote alias to be called `origin` (default value).
Thus as a temporary work-around, you can rename your remote to `origin` using (in @adlternative case):

```
git remote rename github origin
```

(might be related to https://github.com/KnisterPeter/vscode-github/pull/796 and https://github.com/KnisterPeter/vscode-github/pull/774)

**Comment by adlternative** [comment]
> I also just stumbled across this issue (see also [here](https://stackoverflow.com/questions/51524443/heroku-configuration-contains-an-invalid-remotename)).
> My guess is that somehow the regex (`git config --local --get-regexp ^remote.*.url`) is not parsed correctly and the extension is then expecting the remote alias to be called `origin` (default value).
> Thus as a temporary work-around, you can rename your remote to `origin` using (in @adlternative case):
> 
> ```
> git remote rename github origin
> ```
> 
> (might be related to #796 and #774)

Ok, I have renamed it, it's work. I noticed this Regular expression too,  [here](https://github.com/KnisterPeter/vscode-github/blob/612d76581efe8a171687d211fc019766a5767602/src/git.ts#L52),
but I don’t know TypeScript very well :0

**Comment by KnisterPeter** [comment]
TypeScript is not doing anything here. TypeScript adds just typechecking to JavaScript.
The regexp `git config --local --get-regexp ^remote.*.url` here is executed by the git cli application.

**Comment by KnisterPeter** [comment]
By the way: renaming is equally good as defining the remote name in the config. :wink:
