### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Kashif-Hussain-Rajpout** [KnisterPeter/vscode-github#859]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.6`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by KnisterPeter** [comment]
Not helpful
