### ISSUE TITLE
Github retains data of old / nonexisting remotes

### ISSUE THREAD

**Issue by gan-mel** [KnisterPeter/vscode-github#876]
Issue Type: <b>Bug</b>

It is hard to give steps to reproduce, but after trying working with two separate GitHub accounts, having remotes from both, and using the platform for a while, you end up with mixed remotes and ghost remotes appearing and with no way to make VSC forget them.

What I would suggest solving this is a built-in function to clear all data retained by VSC from Github to allow a fresh start.
It would also be nice to have better support for multiple GitHub accounts at the same time as an easy switch.

Extension version: 0.30.6
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

**Comment by KnisterPeter** [comment]
@gan-mel  This is probably not the correct repo to report to. This is an unofficial extension which adds github support.
Please report to the office ones from microsoft.
