### ISSUE TITLE
Feature request: add multiple reviewers by command palette

### ISSUE THREAD

**Issue by asimolmez** [KnisterPeter/vscode-github#90]
If I want to add a request reviewer to my pull request, I am repeating "Request a reviewer for the current pull request" for each. We should enter multiple. 

Additional request: 
- we create a constant reviewers list example: {reviewersGroupName: [username1, username2, username3]}
- we enter  reviewersGroupName to "Request a reviewer for the current pull request" popup.
It can be delicious. 😄  WDYT?

**Comment by KnisterPeter** [comment]
Nice idea. I have to think about how to build the UI for this. In vscode the UI is quite limited.

**Comment by ProLoser** [comment]
I don't think you should bother we hard-coding groups. I think you should just let people append more names and then they do an action when they're complete. The user would then collect a batch of names (or comma delineated) and then send them all at once.

**Comment by KnisterPeter** [comment]
@asimolmez @ProLoser I think the main idea was to have a group of users which you add to a lot of pull requests again and again. Then it would be helpful to have a predefined group of usernames.
I'm still not sure how to create a UI for that case. I would love to have a list of possible user names (like on github) and checkboxes in front of them. That way it would be easy to select but does not require a predefined group.

**Comment by ProLoser** [comment]
I will never use a predefined group. It doesn't make sense, GitHub even has
teams for that.

Can't you just reprompt there user to repeatedly select a username until
they are done?

**Comment by ProLoser** [comment]
@asimolmez Have you tried [using a `CODEOWNERS` file](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)? It pretty much does what you're looking for, it might be the solution to your problem.

Alternatively you could create a github team for all the people and then use that  group alias: `@org/team-name` as the reviewer and they will all get added.
