### ISSUE TITLE
Support for opening PR for current branch

### ISSUE THREAD

**Issue by suan** [KnisterPeter/vscode-github#91]
Looks like there's already support for creating and merging the PR for the current branch, but seems like there's no way to open the PR in a browser?

This would be a very useful feature - even better if it could simply switch to the browser tab (if the PR is already open there) and if one could click on or right click on the PR number in the bottom left in the VSCode window and be taken to the PR in the browser.

**Comment by KnisterPeter** [comment]
This is already possible by the command 'Browse open pull request...' from you command palette.

**Comment by suan** [comment]
Not quite tho - when using that command you still have to find the PR for the current branch in the list (which can be tough in big projects) My request was to have a command which would automatically open the current PR without any additional steps

**Comment by KnisterPeter** [comment]
Will be released with 0.13
