### ISSUE TITLE
Open the currently selected lines on github in the browser

### ISSUE THREAD

**Issue by suan** [KnisterPeter/vscode-github#92]
Would be great to be able to open the currently selected lines in github, just like `https://github.com/tpope/vim-fugitive`'s `:Gbrowse` feature - would be even better if there was an additional option to just copy the URL to your clipboard!

**Comment by KnisterPeter** [comment]
You would like to open the currently open line in your editor in github?
I would prefer the option to copy the line to the clipboard instead of opening it. Would that be okay?

**Comment by suan** [comment]
Actually since I created this issue I've found other plugins that can do this, such as https://github.com/ziyasal/vscode-open-in-github

I'll close the issue
