### ISSUE TITLE
GitHub picking up credentials from .gitconfig rather than from the currenly logged in user of the extension

### ISSUE THREAD

**Issue by srikari-rallabandi-2208** [KnisterPeter/vscode-github#921]
Issue Type: <b>Bug</b>

I wrote a story around the same in my medium post please refer to the same.

https://medium.com/@sreeku.ralla/vscode-github-plung-in-issue-8bc353e9e703

Extension version: 0.30.7
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 7019990c-f19a-4fd7-a9ab-16412b7feefd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710cf:30416617
py55gd98:30419165
vscexrecpromp3c:30407761

```

</details>

**Comment by KnisterPeter** [comment]
This plugin is written around the git cli. That means it has no idea of the authenticated user and the plugin also pre-dates the auth-APIs in vscode.

It would be a huge effort to rewrite everything to use the git in vscode.
Also there is the [official github plugin](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) which does what you expect.
