### ISSUE TITLE
⚠️ It took too long to start up and preventing other extensions to start 

### ISSUE THREAD

**Issue by Battur0116** [KnisterPeter/vscode-github#975]
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.7`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by KnisterPeter** [comment]
Hi @Battur0116, this is not a helpful issue report.
Also this extension is deprecated as you can read here:
https://github.com/KnisterPeter/vscode-github#vscode-github-readme
